### ISSUE TITLE
osquery Incorrectly Reporting "Removed" Items

### ISSUE THREAD

**Issue by clong** [facebook/osquery#3735] opened 2017-09-27 18:31 UTC
OS: OSX 10.12.6
Osquery version: 2.6.1

osquery is generating "removed" events despite the fact that items are not actually being removed. After the remove event has been generated, an "added" event usually follows within a few hours.

As part of some testing I ran yesterday, I created some benign plists that would trigger the "spigot" and "icefog" queries in the osx-attacks pack. I left those plists active in launchd for the last 24 hours and was surprised to notice logs appear with `"action": "removed"` in them relating to the plists. 1-2 hours later, `"action": "added"` events showed up for the same events.

Upon further inspection, this has happened with almost every single osx-attack event from multiple hosts across our fleet, so it is not isolated to a single host. At this point in time, I am uncertain if this is limited to queries from the osx-attacks pack, or if it's an issue with the launchd table, or possibly a caching issue.

Repro scenario: 
1. Add plists to launchd that would trigger the "spigot" and "icefog" queries in osx-attacks pack and ensure they show up in osqueryi when running the respective queries
2. Eventually the schedule query for "spitgot" and "icefog" will run (we schedule 1x per hour) and the first result will show that the item has been removed, even though it hasn't
3. At some later point in time (the interval is not consistent), osquery will log that the item has been "added", even though the item was never removed in the first place

This is a fairly serious problem, because it can lead to an inability to understand if:
a) a malicious artifact has been cleaned up
b) whether a malicious artifact was newly added to the host, or whether the "added" a event is due to a previous erroneous "removed" event 

Screenshot attached:
![screen shot 2017-09-27 at 11 27 31 am](https://user-images.githubusercontent.com/5092699/30930660-2eb99a38-a377-11e7-81ab-12b6cf8afba7.png)

**Comment by Centurion89** [comment] 2017-09-27 18:39
Upon further inspection, I see a few workstations that have "removed" their entire set of launchd plists and then later "added" the entire set back, leading me to think this might be caused by a bad set of results being returned by launchd?

**Comment by theopolis** [comment] 2017-09-27 18:43
The launchd table is one of the worst performing tables. This behavior seems related to exhausting the watchdog limits occasionally while mid-query of launchd. Do you also have status logs indicating that these queries may have failed?

The inverted removed/added symptom would come from storing the results then ending before the query is marked completed.

**Comment by theopolis** [comment] 2017-09-27 18:46
It may be time to rewrite the launchd table too. If you're seeing the whole set removed and no time-correlated error about query failure then something is causing it to return a null-set

**Comment by Centurion89** [comment] 2017-09-27 20:27
Good call. Let me check my status logs and see if I can find any errors/warnings occurring at the same time.

**Comment by Centurion89** [comment] 2017-09-27 20:58
Unfortunately our status logs aren't centralized, but I do have the single logfile on our TLS endpoint. I grepped for `watchdog` and `Scheduled query may have failed`, but don't see any failed queries related to the osx-attacks pack or launchd. 

Any other terms I should be searching for? Happy to try any debugging steps, but not sure what makes sense as a next step.

**Comment by theopolis** [comment] 2017-09-27 23:10
Thanks for checking @Centurion89! For these hosts, is the bug isolated to the `launchd` table (and queries that use it)? Are there any other table results that have the large `removed` followed by `added` series of events? Then if so, are they correlated by time? As in, do all queries begin to return no results at the same time?

It seems like a least-common-denominator causing this effect is the `launchd` being queried correctly, then returning no results. When the empty result set is compared against the previous select it looks like ALL of the rows have been `removed`, these removals will propagate into all other queries using the `launchd` table due to table caching (e.g., `SELECT * FROM launchd` is cached for `SELECT * FROM launchd WHERE path LIKE /some/path` within smaller intervals from the wide-select).

**Comment by Centurion89** [comment] 2017-09-28 01:20
@theopolis my initial triage shows this seems to be happening on a few tables:
• crashes (multiple additions/removals for the same crash_path)
• launchd (multiple additions/removals for the same path)
• last (multiple additions/removals for the same timestamp)

There are possibly more, but these are the ones I'm able to quickly confirm.

I think screenshots of the data mostly does a better job of displaying the issue than I can explain it. A few examples below:

The `last` table shows the same event (time and pid are identical) being added and removed multiple times on some hosts:
![screen shot 2017-09-27 at 5 51 18 pm](https://user-images.githubusercontent.com/5092699/30944554-7de4c0f2-a3ad-11e7-8db5-26229c09b0f7.png)

Launchd table shows a host who has had the same set of plists added 6 times (I manually verified nothing in the plists changed that should cause a new event to be recorded. There are no corresponding "removed" events though):
![screen shot 2017-09-27 at 6 01 23 pm](https://user-images.githubusercontent.com/5092699/30944633-184d0816-a3ae-11e7-8339-819bf54cf5bc.png)

I think the things that these tables have in common is that they're probably the least performant and generate the largest datasets in their results. However, I'm not seeing many errors about queries failing or watchdog triggering in our status logs. And yeah, all the "removed" events happen en-masse at the exact same time, followed by the events being added-back in en-masse with an identical timestamp -- i.e.: 86 events get "removed" from `last` at 1:15pm  and then 86 events get "added" from `last` at 3:15pm

I think low performing tables returning no results is probably the root cause here, but I'm not sure I'm seeing correlated warning/error logs when this is happening. However, our status logfile is not well monitored, so let me follow up that situation and see if I'm wrong about the error messages.

**Comment by theopolis** [comment] 2017-09-28 02:31
Another indicator could be the `pid` of `osqueryd` before the events and after. A different `pid` means there was a watchdog "event" ;)

**Comment by Centurion89** [comment] 2017-09-28 19:03
@theopolis any idea if watchdog events would generate an entry in the osx crashes table?

**Comment by Centurion89** [comment] 2017-09-28 19:18
After digging into this issue more, it's affecting many more tables than the ones I mentioned above. Also definitively seeing this with:

• firefox_addons
• carbon_black_info
• startup_items

**Comment by spasam** [comment] 2017-09-28 19:29
I have been passively following this thread and thought it was isolated to launchd. Looks like it is more widespread. Let me try to reproduce this on Linux with other tables.

**Comment by Centurion89** [comment] 2017-09-28 20:38
@spasam I'm actually not seeing this behavior on Linux at the moment, but happy to have more eyes on this issue.

**Comment by Centurion89** [comment] 2017-09-28 22:28
Good news! I just re-tested on 2.7.0 and am *not* seeing the issue there. I don't want to mark this as resolved without independent confirmation, but may do another test on another machine and see if I can both reproduce and see the fix by upgrading there as well.

**Comment by Centurion89** [comment] 2017-10-04 20:54
Disregard previous (now deleted) comment. Just had this issue reoccur on my 2.7.0 install. Will upgrade to 2.8.0 today and see if it continues.

**Comment by spasam** [comment] 2017-10-19 17:59
@Centurion89 Are you still seeing this in 2.9.x?

**Comment by Centurion89** [comment] 2017-10-19 18:06
@spasam Unfortunately we don't have 2.9.x deployed to our fleet yet. Was something committed that would have helped address this issue?

**Comment by Centurion89** [comment] 2017-11-21 22:29
We're deploying 2.10.2 to OSX this week. Will follow up in 1-2 weeks and determine whether this continues to be a bug or if it can be closed out

**Comment by theopolis** [comment] 2018-01-06 04:42
Will close for now, if this is still an issue, let's investigate again.

**Closed by theopolis** 2018-01-06 04:42 UTC
Labels: triage
