### ISSUE TITLE
deploy: osquery.db and extensions folder permissions are inconsistent

### ISSUE THREAD

**Issue by kemalbayar** [facebook/osquery#4172] opened 2018-03-02 08:17 UTC
After osquery.msi installation, related to permissions, the osquery.db folder’s owner is setted as SYSTEM so the folder isn’t accessible by the other users(admins,users...) 

but with choco method...

![image](https://user-images.githubusercontent.com/33925821/36889490-3c024a50-1e0b-11e8-8a9a-a45d2bcf4932.png)

**Comment by muffins** [comment] 2018-03-02 18:46
@kemalbayar those permissions for the `Users` group look correct. Users should be able to enumerate the directory, read, and execute, but they should have no write permissions. Can you be more specific about the error or problem that you're experiencing? The osquery database is not something that's _supposed_ to be accessible. What use case do you have for modifying or accessing the DB?

**Comment by kemalbayar** [comment] 2018-03-04 14:17
what i'm trying to point out that why one method is different from the other one.
for example: the following image shows the status after the OSQuery.msi installation.  By this method, 
I can't access to the folder with Admin account. However after choco method, I can access to the same folder with the same account

![image](https://user-images.githubusercontent.com/33925821/36946313-2b901888-1fcc-11e8-8d05-aa85479f9ef0.png)

**Comment by kemalbayar** [comment] 2018-03-05 08:19
in addition, I think due to above permission situation, I got the error `osqueryd initialize failed: Could not initialize database'

![image](https://user-images.githubusercontent.com/33925821/36964226-01507d2e-2067-11e8-8ffb-6ef0b1805c6b.png)

**Comment by kemalbayar** [comment] 2018-03-05 14:48
it's weird but today I've encountered a different issue with chocolatey... I installed osquery using choco and I can't access the osquery.db folder due to permission problem. I see that the Folder owner is SYSTEM and there is no problem when I start the osqueryd service but I use the command   \ProgramData\osquery\osqueryd\osqueryd.exe --flagfile=\ProgramData\osquery\osquery.flags --verbose --tls_dump=true
on cmd.exe,  I got that Error: E0305 17:19:48.687312  4748 init.cpp:591] [Ref #1629] osqueryd initialize failed: Could not initialize database

**Comment by muffins** [comment] 2018-03-05 18:27
Yeah the issue here is just that our permissions seem to not be applied in a consistent manner, but this shouldn't cause any issue with the daemon running. The situation you've found with the chocolatey install and then the fail to init the DB is an issue, but again the cause is known. I'll try and get a fix up for the permissions consistency issues, but for the fail to intialize the database folks have found the best fix is to blow away the DB and relaunch the daemon.

**Comment by kemalbayar** [comment] 2018-03-06 14:33
Today, I did a test again on this issue... I installed osquery via chocolatey and...
1- I can access to the osquery.db folder by "Administrator" account
2-the owner of the folder is setted as "Administrators" (as groups)
3- the following picture demonstrate it

![image](https://user-images.githubusercontent.com/33925821/37037921-6a6c2e86-2164-11e8-8abf-8a5d3f54130f.png)

**Comment by kemalbayar** [comment] 2018-03-13 11:53
@muffins  also there is a different but related issue.

I installed osquery on Windows 10 system using the latest osquery.msi from the site, after the installation some Deny entries exists in permissions as shown in the picture.
In this state, without changing the permission entries manually, osquery.db folder cant be accessible

**Comment by muffins** [comment] 2018-03-14 05:06
Right that’s the expectation though, as the MSI uses Dent-Writes currently, but that shouldn’t matter as the goal of these permission sets is just to ensure that no lower privileged uses have access to modify the DB.

**Comment by uncletimmy3** [comment] 2018-03-30 11:43
@muffins It's a bad idea and useless to use Deny_rules in Windows OS for SYSTEM and BUILTIN\Administrators, beacsuse they have rights to become owners of any objects in Windows OS.
It would be better if permisson inheritance is disabled and necessary rights are granted. For example:
![default](https://user-images.githubusercontent.com/34276679/38136645-4ecc457a-3439-11e8-96d1-57abdde08eff.JPG)

In this case nobody have access to folder, subfolders and files  except SYSTEM, BUILTIN\Administrators and  Owners.

**Comment by kemalbayar** [comment] 2018-03-30 11:57
Deny is always the highest priority so I think it's possible to manage without Deny entries

**Comment by oligarx** [comment] 2018-04-03 17:45
Does anyone have a proper work-around for this issue? Can't get the service to work

**Comment by muffins** [comment] 2018-09-18 16:56
This is addressed in #5229

**Comment by muffins** [comment] 2018-09-19 20:52
Closing this out for now, as the permissions for the database have been greatly relaxed.

**Closed by muffins** 2018-09-19 20:52 UTC
Labels: Windows, deployment, user experience
