### ISSUE TITLE
windows osqueryd: Could not initialize database

### ISSUE THREAD

**Issue by shashial** [facebook/osquery#5251] opened 2018-10-08 18:00 UTC
# Bug report

### What operating system and version are you using?
+----------+-------+----------+
| version  | build | platform |
+----------+-------+----------+
| 6.1.7601 | 7601  | windows  |
+----------+-------+----------+
*this also works on windows 10 1803 and windows 10 1709, i assume it works on all other windows versions as vell.

### What version of osquery are you using?

3.2.8 and
+---------+
| version |
+---------+
| 3.3.0   |
+---------+
on different machines

### What steps did you take to reproduce the issue?

![photo_2018-10-08_20-46-16](https://user-images.githubusercontent.com/10578726/46625061-3c4d2d80-cb3b-11e8-8565-93d3fed7f960.jpg)

just randomly run this three commands:
Start-Service osqueryd
Stop-Service osqueryd
 C:\programdata\osquery\osqueryd\osqueryd.exe

### What did you expect to see?

I did expect osqueryd to launch.
### What did you see instead?
[E1008 20:26:36.127249  3676 init.cpp:608] [Ref #1629] osqueryd initialize failed: Could not initialize database
and sometimes it is 
[E1008 19:02:11.033499  2224 init.cpp:574] Cannot activate filesystem logger plugin: Could not create file: \ProgramData\osquery\log\osqueryd.results.log

Furthermore, this "bug" sometimes occurs by itself(without me randomly running these commands), just by osquery daemon, i.e. 7\10 user workstations(different windows versions) with osquery running finished up in this state: daemon is running, but database is not updated. 
When we were watching "broken" osquery process under windbg, it was clear that the process was waiting for the database to be "released".

Feel free to ask any details about an issue.

**Comment by groob** [comment] 2018-10-09 16:33
This is (hopefully) fixed with 3.3.1 https://github.com/facebook/osquery/pull/5229

The workaround for this, is to change the `--database_path` and try to launch again.

**Comment by vivekuppal** [comment] 2018-10-09 19:15
I was able to reproduce this issue locally on a laptop. I captured the attached procmon file for the failure. 
The db name specified in the flags file is `kolide.db`. 

Rename the  file to `.pml` file if needed. 
Search for process = `osqueryd.exe`. 
[osq-5251.log](https://github.com/facebook/osquery/files/2461848/osq-5251.log)

**Comment by shashial** [comment] 2018-10-10 11:45
> This is (hopefully) fixed with 3.3.1 #5229
> 
> The workaround for this, is to change the `--database_path` and try to launch again.

It seems that the problem with database indeed was fixed and i thank you for noting that, but there was also another one with log file(it also sometimes happened in the previous 3.3.0 version, but i did not mention it).

`[E1010 04:09:58.107646  7608 init.cpp:593] Cannot activate filesystem logger plugin: Could not create file: \ProgramData\osquery\log\osqueryd.results.log `

i understand that deleting log file is kind of a solution, but it is a pain to do that on hundreds of workstations every <event>. (Here i must repeat myself that this regularly happens on user workstations after rebooting them or putting them into hibernate/sleep states.)  

In the screenshot below version/os is shown, besides steps to reproduce(they are the same) and also that deleting log file solves an issue.

![win_osquery](https://user-images.githubusercontent.com/10578726/46733643-8cda9d00-cc99-11e8-92bd-c627b0bcadf3.jpg)

**Comment by vivekuppal** [comment] 2018-10-10 14:19
@shashial were you able to validate in an environment that the original issue of `osqueryd initialize failed: could not initialize database` was fixed with PR #5229 .

**Comment by groob** [comment] 2018-10-10 17:14
Not being able to create the log file smells like UAC to me. 
Are you starting osquery in an admin shell? Do you have UAC enabled? Does your usare have the right to create files/folders in that directory?

**Comment by vivekuppal** [comment] 2018-10-11 01:33
Thanks to @groob we created a 3.3.1 windows version of osquery and tried it on the failing windows machines. Anecdotal testing on 2 machines shows that PR#5229 fixes this issue.

**Comment by shashial** [comment] 2018-10-11 08:57
@vivekuppal i have not met this problem again (yet), so i think yes. will be able to tell you with certainty after running tests on all machines.
@groob 
>Are you starting osquery in an admin shell? 

yes, proofs are on scrins below
> Do you have UAC enabled?

yes, proofs are on scrins below
> Does your user have the right to create files/folders in that directory?

yes, proofs are on scrins below

so this sometimes works fine(here you can see all the proofs from above AND the fact that osqueryd did launched just fine)
![11](https://user-images.githubusercontent.com/10578726/46792724-af79be00-cd4c-11e8-8b43-f81da2559fc3.jpg)


on this screenshot you can see me deleting the whole folder and creating it again (UAC = 1, admin shell, nothing changed). the bug occurs twice.
![2](https://user-images.githubusercontent.com/10578726/46792216-87d62600-cd4b-11e8-94c1-da75162dc0e7.jpg)

log file permissions
![3](https://user-images.githubusercontent.com/10578726/46792243-9d4b5000-cd4b-11e8-9aad-10e78af29e35.jpg)

and the final one. i did delete the file with my mouse from desktop environment, and....
it's a kind of magic, this works just fine.

![4](https://user-images.githubusercontent.com/10578726/46792441-0af77c00-cd4c-11e8-9614-cde0e5474765.jpg)

**Comment by shashial** [comment] 2018-10-11 14:15
It seems that i have just figured out what the problem is.
command `icacls c:\programdata\osquery\log /t /c`

this does not work (start service -> start osqueryd manually)
> c:\programdata\osquery\log\osqueryd.results.log 
>                                                 NT AUTHORITY\SYSTEM:(DENY)(S,X)
>                                                 NT AUTHORITY\SYSTEM:(R,W,D,WDAC)
>                                                 BUILTIN\Administrators:(DENY)(W,D,X)
>                                                 BUILTIN\Administrators:(R)
>                                                 BUILTIN\Users:(DENY)(W,D,X)
>                                                 BUILTIN\Users:(R)
>                                                 Everyone:(DENY)(W,D,RD,REA,X,RA)
>                                                 Everyone:(Rc)
>                                                 NT AUTHORITY\SYSTEM:(I)(F)
>                                                 BUILTIN\Administrators:(I)(F)
>                                                 BUILTIN\Users:(I)(RX)

but this works just fine in both cases (start osqueryd manually -> start service)
> c:\programdata\osquery\log\osqueryd.results.log 
>                                                 BUILTIN\Administrators:(DENY)(S,X)
>                                                 BUILTIN\Administrators:(R,W,D,WDAC)
>                                                 NT AUTHORITY\SYSTEM:(DENY)(W,D,X)
>                                                 NT AUTHORITY\SYSTEM:(R)
>                                                 BUILTIN\Users:(DENY)(W,D,X)
>                                                 BUILTIN\Users:(R)
>                                                 Everyone:(DENY)(W,D,RD,REA,X,RA)
>                                                 Everyone:(Rc)
>                                                 NT AUTHORITY\SYSTEM:(I)(F)
>                                                 BUILTIN\Administrators:(I)(F)
>                                                 BUILTIN\Users:(I)(RX)

**Comment by groob** [comment] 2018-10-11 17:06
you can't start a service and osqueryd.exe at the same time. One will be locked out due to trying to access the same resources. What is your goal here? either you're using the service, or you're not.

**Comment by shashial** [comment] 2018-10-11 17:19
@groob 
but wait, first of all i do stop service before i launch the osqueryd.exe binary and vice versa, means they do not work at the same time, either in turns.

and second - this causes osqueryd "crushes" on users machines, means this bug affects stability.

**Comment by shashial** [comment] 2018-10-12 16:33
@groob update: i was able to "fix" the problem, but not properly. the problem is in 
`filesystem\filesystem.cpp`

i did just comment these lines, works fine now. permissions are inherited from the 'log' folder.

```
  if (!platformChmod(path.string(), permissions)) {
    // Could not change the file to the requested permissions.
    return Status(1, "Failed to change permissions for file: " + path.string());
  }
```
 
Something like the #5229 patch should solve it, because the problem is basically the same, but about files instead of the databases.

**Comment by muffins** [comment] 2018-10-22 16:57
Before we triage this too much, can you check out if 3.3.1 fixes the issues? There's _considerable_ updates to the osquery database behaviors on Windows in 3.3.1, and it might've remediated the issues you're seeing.

**Comment by shashial** [comment] 2018-10-23 12:57
> Before we triage this too much, can you check out if 3.3.1 fixes the issues? There's _considerable_ updates to the osquery database behaviors on Windows in 3.3.1, and it might've remediated the issues you're seeing.

i might not have said that clear enough, but everything written after https://github.com/facebook/osquery/issues/5251#issuecomment-428540994 was written **about 3.3.1** version.

long story short:
1) the database error was fixed(at least we are unable to reproduce it)
2) the error with log_file was not.
> [ E1011 01:32:26.936301 8260 init.cpp:593] Cannot activate filesystem logger plugin: Could not create file: \ProgramData\osquery\log\osqueryd.results.log

p.s. if this would be of any help to you: we found out that each time the log file error occures, an error 
> W1023 12:41:00.407903   372 config.cpp:563] Error parsing the config JSON  source C:\programdata\osquery\osquery.conf Cannot parse JSON: The document is empty. 

occures either. but since it can be related to our attempts to fix the logfile error, and it's true nature is unknown, i'll just leave this information here, but i think this most likely is connected to the current issue.

**Comment by muffins** [comment] 2019-01-28 17:23
@shashial got it! Thanks, for that. Would you mind cutting a new issue or pinging the #general/#windows slack channels with the _new_ issues you're seeing? As this issue was largely related to issues with initializing the database, and that problem is remediated, I'm going to close this issue out.

That being said -- a quick glance through your problem, can you double check the permissions on the `C:\ProgramData\osquery\log` folder? It needs to be writeable by `SYSTEM` or `Administrator`, whichever osquery is running as, then further the line
> W1023 12:41:00.407903 372 config.cpp:563] Error parsing the config JSON source C:\programdata\osquery\osquery.conf Cannot parse JSON: The document is empty.
To me indicates that there's some issue with your JSON. Use a utility like `jq` to try and sort out if there's something wrong with your JSON format, and ensure that the encoding of the file is utf-8. If neither of those steps help, please hit up the Slack, as this looks like an environment issue from a glance.

Thanks!

**Closed by muffins** 2019-01-28 17:23 UTC
Labels: Windows, database
