### ISSUE TITLE
config options not respected via config file

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#577] opened 2015-01-07 00:31 UTC
https://gist.github.com/maus-/91b45eebd38ea5bfa3bb

**Comment by theopolis** [comment] 2015-01-07 03:29
These and QueryContext methods need unit tests.

**Comment by theopolis** [comment] 2015-01-07 04:04
Looks like the config options are working for my build on master.

```bash
[reed@reed-mbp] ~/git/github/osquery(branch:master) » ./build/darwin/osquery/osqueryd --config_path ~/osquery-custom.conf --verbose_debug
I0106 19:59:39.748733 1895277328 registry.h:65] ConfigPlugins[filesystem] registered
I0106 19:59:39.749178 1895277328 registry.h:65] LoggerPlugins[glog] registered
I0106 19:59:39.749222 1895277328 registry.h:65] EventPublishers[FSEventsEventPublisher] registered
I0106 19:59:39.749245 1895277328 registry.h:65] EventPublishers[IOKitHIDEventPublisher] registered
I0106 19:59:39.749269 1895277328 registry.h:65] EventPublishers[SCNetworkEventPublisher] registered
I0106 19:59:39.749291 1895277328 registry.h:65] LoggerPlugins[filesystem] registered
I0106 19:59:39.749339 1895277328 registry.h:65] TablePlugins[file] registered
I0106 19:59:39.749364 1895277328 registry.h:65] TablePlugins[hash] registered
I0106 19:59:39.749393 1895277328 registry.h:65] TablePlugins[osquery_flags] registered
I0106 19:59:39.749418 1895277328 registry.h:65] TablePlugins[osquery_info] registered
I0106 19:59:39.749444 1895277328 registry.h:65] TablePlugins[time] registered
I0106 19:59:39.749472 1895277328 registry.h:65] EventSubscribers[PasswdChangesEventSubscriber] registered
I0106 19:59:39.749495 1895277328 registry.h:65] EventSubscribers[HardwareEventSubscriber] registered
I0106 19:59:39.749524 1895277328 registry.h:65] TablePlugins[alf] registered
I0106 19:59:39.749550 1895277328 registry.h:65] TablePlugins[alf_exceptions] registered
I0106 19:59:39.749572 1895277328 registry.h:65] TablePlugins[alf_explicit_auths] registered
I0106 19:59:39.749596 1895277328 registry.h:65] TablePlugins[alf_services] registered
I0106 19:59:39.749630 1895277328 registry.h:65] TablePlugins[apps] registered
I0106 19:59:39.749655 1895277328 registry.h:65] TablePlugins[arp_cache] registered
I0106 19:59:39.749685 1895277328 registry.h:65] TablePlugins[ca_certs] registered
I0106 19:59:39.749711 1895277328 registry.h:65] TablePlugins[cpuid] registered
I0106 19:59:39.749739 1895277328 registry.h:65] TablePlugins[crontab] registered
I0106 19:59:39.749761 1895277328 registry.h:65] TablePlugins[etc_hosts] registered
I0106 19:59:39.749794 1895277328 registry.h:65] TablePlugins[etc_services] registered
I0106 19:59:39.749817 1895277328 registry.h:65] TablePlugins[groups] registered
I0106 19:59:39.749846 1895277328 registry.h:65] TablePlugins[hardware_events] registered
I0106 19:59:39.749869 1895277328 registry.h:65] TablePlugins[homebrew_packages] registered
I0106 19:59:39.749893 1895277328 registry.h:65] TablePlugins[interface_addresses] registered
I0106 19:59:39.749924 1895277328 registry.h:65] TablePlugins[interface_details] registered
I0106 19:59:39.749951 1895277328 registry.h:65] TablePlugins[kextstat] registered
I0106 19:59:39.749982 1895277328 registry.h:65] TablePlugins[last] registered
I0106 19:59:39.750025 1895277328 registry.h:65] TablePlugins[launchd] registered
I0106 19:59:39.750048 1895277328 registry.h:65] TablePlugins[listening_ports] registered
I0106 19:59:39.750072 1895277328 registry.h:65] TablePlugins[logged_in_users] registered
I0106 19:59:39.750103 1895277328 registry.h:65] TablePlugins[mounts] registered
I0106 19:59:39.750125 1895277328 registry.h:65] TablePlugins[nvram] registered
I0106 19:59:39.750155 1895277328 registry.h:65] TablePlugins[osx_version] registered
I0106 19:59:39.750181 1895277328 registry.h:65] TablePlugins[passwd_changes] registered
I0106 19:59:39.750207 1895277328 registry.h:65] TablePlugins[pci_devices] registered
I0106 19:59:39.750306 1895277328 registry.h:65] TablePlugins[process_envs] registered
I0106 19:59:39.750346 1895277328 registry.h:65] TablePlugins[process_open_files] registered
I0106 19:59:39.750387 1895277328 registry.h:65] TablePlugins[processes] registered
I0106 19:59:39.750418 1895277328 registry.h:65] TablePlugins[routes] registered
I0106 19:59:39.750447 1895277328 registry.h:65] TablePlugins[shell_history] registered
I0106 19:59:39.750480 1895277328 registry.h:65] TablePlugins[startup_items] registered
I0106 19:59:39.750506 1895277328 registry.h:65] TablePlugins[suid_bin] registered
I0106 19:59:39.750551 1895277328 registry.h:65] TablePlugins[usb_devices] registered
I0106 19:59:39.750581 1895277328 registry.h:65] TablePlugins[users] registered
I0106 19:59:39.750608 1895277328 registry.h:65] TablePlugins[xprotect_entries] registered
I0106 19:59:39.750634 1895277328 registry.h:65] TablePlugins[xprotect_reports] registered
I0106 19:59:39.752285 1895277328 config.cpp:62] Setting flag option: config_retriever=filesystem
I0106 19:59:39.752337 1895277328 config.cpp:62] Setting flag option: db_path=/tmp/osquery.db
I0106 19:59:39.752396 1895277328 config.cpp:62] Setting flag option: disable_logging=false
I0106 19:59:39.752429 1895277328 config.cpp:62] Setting flag option: event_pubsub=true
I0106 19:59:39.752465 1895277328 config.cpp:62] Setting flag option: event_pubsub_expiry=86000
I0106 19:59:39.752496 1895277328 config.cpp:62] Setting flag option: host_identifier=hostname
I0106 19:59:39.752527 1895277328 config.cpp:62] Setting flag option: log_receiver=filesystem
I0106 19:59:39.752557 1895277328 config.cpp:62] Setting flag option: log_result_events=true
I0106 19:59:39.752586 1895277328 config.cpp:62] Setting flag option: osquery_log_dir=/var/log/osquery
I0106 19:59:39.752760 1895277328 config.cpp:62] Setting flag option: pidfile=/tmp/osquery.pid
I0106 19:59:39.752822 1895277328 config.cpp:62] Setting flag option: schedule_splay_percent=10
I0106 19:59:39.752866 1895277328 config.cpp:62] Setting flag option: use_in_memory_database=false
I0106 19:59:39.752930 1895277328 config.cpp:62] Setting flag option: worker_threads=4
I0106 19:59:39.752941 1895277328 config.cpp:71] Changing the interval for processtest from  30 to 33
I0106 19:59:39.752950 1895277328 config.cpp:71] Changing the interval for aprtest from  110 to 113
I0106 19:59:39.753190 1895277328 system.cpp:176] Writing pid (84261) to /tmp/osquery.pid
I0106 19:59:39.757108 1895277328 daemon.cpp:54] Listing all plugins
I0106 19:59:39.757133 1895277328 daemon.cpp:56] Logger plugins:
I0106 19:59:39.757148 1895277328 daemon.cpp:58]   - filesystem
I0106 19:59:39.757161 1895277328 daemon.cpp:58]   - glog
I0106 19:59:39.757174 1895277328 daemon.cpp:61] Config plugins:
I0106 19:59:39.757185 1895277328 daemon.cpp:63]   - filesystem
I0106 19:59:39.757197 1895277328 daemon.cpp:66] Event Publishers:
I0106 19:59:39.757210 1895277328 daemon.cpp:68]   - SCNetworkEventPublisher
I0106 19:59:39.757220 1895277328 daemon.cpp:68]   - IOKitHIDEventPublisher
I0106 19:59:39.757232 1895277328 daemon.cpp:68]   - FSEventsEventPublisher
I0106 19:59:39.757243 1895277328 daemon.cpp:71] Event Subscribers:
I0106 19:59:39.757256 1895277328 daemon.cpp:73]   - HardwareEventSubscriber
I0106 19:59:39.757266 1895277328 daemon.cpp:73]   - PasswdChangesEventSubscriber
I0106 19:59:39.757488 266678272 scheduler.cpp:132] osquery::initializeScheduler
^C
------------------------------------------------------------
[reed@reed-mbp] ~/git/github/osquery(branch:master) » cat ~/osquery-custom.conf
{
  "options": {
    "osquery_log_dir": "/var/log/osquery",
    "db_path": "/tmp/osquery.db",
    "pidfile": "/tmp/osquery.pid",
    "lockfile": "/var/lock/subsys/osquery",
    "config_retriever": "filesystem",
    "debug": "false",
    "disable_logging": "false",
    "event_pubsub": "true",
    "event_pubsub_expiry": "86000",
    "host_identifier": "hostname",
    "log_receiver": "filesystem",
    "log_result_events": "true",
    "schedule_splay_percent": "10",
    "use_in_memory_database": "false",
    "verbose_debug": "false",
    "worker_threads": "4"
  },
  "scheduledQueries": [
    {
      "name": "processtest",
      "query": "SELECT * FROM processes;",
      "interval": 30
    },
    {
      "name": "aprtest",
      "query": "SELECT * FROM arp_cache;",
      "interval": 110
    }
  ]
}
------------------------------------------------------------
[reed@reed-mbp] ~/git/github/osquery(branch:master) » ls /tmp/osquery.*
/tmp/osquery.pid

/tmp/osquery.db:
000003.log      CURRENT         IDENTITY        LOCK            LOG             MANIFEST-000004
```

**Comment by theopolis** [comment] 2015-01-11 08:57
I haven't been able to reproduce this. @maus-, if you get a chance can you checkout the `--verbose_debug` flag and see if the options setters are logging?

**Comment by maus-** [comment] 2015-01-12 18:24
[root@localhost ~]# osqueryd --config_path=/etc/osquery/osquery.conf --verbose_debug
    I0112 18:07:24.591248  4109 registry.h:57] TablePlugins[    arp_cache] registered
    I0112 18:07:24.591665  4109 registry.h:57] TablePlugins[    block_devices] registered
    I0112 18:07:24.591732  4109 registry.h:57] TablePlugins[    cpuid] registered
    I0112 18:07:24.591764  4109 registry.h:57] TablePlugins[    crontab] registered
    I0112 18:07:24.591781  4109 registry.h:57] TablePlugins[    etc_hosts] registered
    I0112 18:07:24.591797  4109 registry.h:57] TablePlugins[    etc_services] registered
    I0112 18:07:24.591814  4109 registry.h:57] TablePlugins[file]     registered
    I0112 18:07:24.591830  4109 registry.h:57] TablePlugins[    groups] registered
    I0112 18:07:24.591851  4109 registry.h:57] TablePlugins[    hardware_events] registered
    I0112 18:07:24.591867  4109 registry.h:57] TablePlugins[hash]     registered
    I0112 18:07:24.591889  4109 registry.h:57] TablePlugins[    kernel_modules] registered
    I0112 18:07:24.591908  4109 registry.h:57] TablePlugins[last]     registered
    I0112 18:07:24.591923  4109 registry.h:57] TablePlugins[    logged_in_users] registered
    I0112 18:07:24.591941  4109 registry.h:57] TablePlugins[    mounts] registered
    I0112 18:07:24.591959  4109 registry.h:57] TablePlugins[    osquery_flags] registered
    I0112 18:07:24.591974  4109 registry.h:57] TablePlugins[    osquery_info] registered
    I0112 18:07:24.591992  4109 registry.h:57] TablePlugins[    passwd_changes] registered
    I0112 18:07:24.592008  4109 registry.h:57] TablePlugins[    pci_devices] registered
    I0112 18:07:24.592025  4109 registry.h:57] TablePlugins[    port_inode] registered
    I0112 18:07:24.592041  4109 registry.h:57] TablePlugins[    process_envs] registered
    I0112 18:07:24.592056  4109 registry.h:57] TablePlugins[    process_open_files] registered
    I0112 18:07:24.592074  4109 registry.h:57] TablePlugins[    processes] registered
    I0112 18:07:24.592092  4109 registry.h:57] TablePlugins[    routes] registered
    I0112 18:07:24.592108  4109 registry.h:57] TablePlugins[    rpm_packages] registered
    I0112 18:07:24.592123  4109 registry.h:57] TablePlugins[    shell_history] registered
    I0112 18:07:24.592139  4109 registry.h:57] TablePlugins[    socket_inode] registered
    I0112 18:07:24.592154  4109 registry.h:57] TablePlugins[    suid_bin] registered
    I0112 18:07:24.592166  4109 registry.h:57] TablePlugins[time]     registered
    I0112 18:07:24.592182  4109 registry.h:57] TablePlugins[    usb_devices] registered
    I0112 18:07:24.592200  4109 registry.h:57] TablePlugins[    users] registered
    I0112 18:07:24.592223  4109 registry.h:57] ConfigPlugins[    filesystem] registered
    I0112 18:07:24.592244  4109 registry.h:57] LoggerPlugins[    glog] registered
    I0112 18:07:24.592263  4109 registry.h:57] EventPublishers[    INotifyEventPublisher] registered
    I0112 18:07:24.592278  4109 registry.h:57] EventPublishers[    UdevEventPublisher] registered
    I0112 18:07:24.592293  4109 registry.h:57] LoggerPlugins[    filesystem] registered
    I0112 18:07:24.592313  4109 registry.h:57] EventSubscribers[    PasswdChangesEventSubscriber] registered
    I0112 18:07:24.592326  4109 registry.h:57] EventSubscribers[    HardwareEventSubscriber] registered
    I0112 18:07:24.592355  4109 system.cpp:168] Writing pid     (4109) to /var/osquery/osqueryd.pidfile
    E0112 18:07:24.592370  4109 daemon.cpp:20] Could not create     osquery pidfile: Could not create file
    
    ------------------------------------------------------------
    
        {
      "options": {
        "osquery_log_dir": "/var/log/osquery",
        "db_path": "/tmp/osquery/osquery.db",
        "pidfile": "/var/run/osquery.pid",
        "lockfile": "/var/lock/subsys/osquery",
        "config_retriever": "filesystem",
        "debug": "false",
        "disable_logging": "false",
        "event_pubsub": "true",
        "event_pubsub_expiry": "86000",
        "host_identifier": "hostname",
        "log_receiver": "filesystem",
        "log_result_events": "true",
        "schedule_splay_percent": "10",
        "use_in_memory_database": "false",
        "verbose_debug": "false",
        "worker_threads": "4"
      },
      "scheduledQueries": [
        {
          "name": "processtest",
          "query": "SELECT * FROM processes;",
          "interval": 30
        },
        {
          "name": "aprtest",
          "query": "SELECT * FROM arp_cache;",
          "interval": 110
        }
      ]
    }

**Comment by theopolis** [comment] 2015-01-12 20:24
I'm stumped, unless gflags is having trouble parsing `=`, which I've seen when trying to expand `~` in paths?

Try:
```
osqueryd --config_path /etc/osquery/osquery.conf --verbose_debug
```

as an alternate?

**Comment by maus-** [comment] 2015-01-12 22:16
Looks like I have this now working with the latest build. its safe to say to close this issue.

**Closed** 2015-01-13 02:11 UTC
Labels: needs response, question
