### ISSUE TITLE
Windows: Thrift message: TServerTransport died: TPipeServer: client connection failed

### ISSUE THREAD

**Issue by stachdude** [facebook/osquery#2991] opened 2017-02-10 13:35 UTC
Hello yet again.

This time we are on master branch commit https://github.com/facebook/osquery/commit/6ab460f5db6fa8fc64f1c6170bed746093daaebd.

Windows 7 (Pro and Enterprise)

Now we caught an issue where an agent after receiving scheduled query, looses connection, but the process it self is alive.

We are sending this query:
```
SELECT name, path, pid FROM processes WHERE on_disk = 0;
```

And now for the interesting part, if the process is running as a Local System, we get 
```
I0210 13:37:24.898167  5864 scheduler.cpp:69] Executing scheduled query ioc_gene
ral_process_on_disk_ac950687: SELECT name, path, pid FROM processes WHERE on_dis
k = 0;
I0210 13:37:24.976168  5128 interface.cpp:86] Thrift message: TPipeServer Connec
tNamedPipe GLE=errno = 995
I0210 13:37:24.976168  5128 interface.cpp:86] Thrift message: TServerTransport d
ied: TPipeServer: client connection failed
```

And the communication never comes back, agent is just running no more logs, nothing. But, if we run the same agent with the same config with Administrator account we get:

```
I0210 14:00:45.029101  7124 scheduler.cpp:69] Executing scheduled query ioc_gene
ral_process_on_disk_ac950687: SELECT name, path, pid FROM processes WHERE on_dis
k = 0;
I0210 14:00:45.196118  7124 query.cpp:68] Storing initial results for new schedu
led query: ioc_general_process_on_disk_ac950687
I0210 14:00:45.029101  7124 scheduler.cpp:69] Executing scheduled query ioc_gene
ral_process_on_disk_ac950687: SELECT name, path, pid FROM processes WHERE on_dis
k = 0;
I0210 14:00:45.196118  7124 query.cpp:68] Storing initial results for new schedu
led query: ioc_general_process_on_disk_ac950687
```

And everything is running smoothly.

Here are the flags we use:

```
--tls_hostname=<hostname>
--tls_server_certs=C:\ProgramData\osquery\crt.crt
--pidfile=C:\ProgramData\osquery\osquery.pid
--enroll_tls_endpoint=/osquery/enroll
--enroll_secret_path=C:\ProgramData\osquery\enroll
--config_plugin=tls
--config_tls_endpoint=/osquery/config
--config_tls_refresh=120
--logger_plugin=tls
--logger_tls_endpoint=/osquery/log
--logger_tls_period=120
--disable_distributed=false
--distributed_plugin=tls
--distributed_tls_read_endpoint=/osquery/distributed/read
--distributed_tls_write_endpoint=/osquery/distributed/write
--distributed_interval=60
--disable_audit=false
--disable_database=true
--disable_events=true
--audit_allow_config=true
--audit_persist=true
```

Also on a side note, we checked the access right, and Local System

**Comment by srozb** [comment] 2017-02-13 09:10
Looks like osquery will always crash when executed as a `SYSTEM` user and the processes table is being queried. 

Steps I took to reproduce the crash:
```
1. psexec64.exe -i -s -d cmd
2. osqueryi.exe --verbose
3. SELECT * FROM processes LIMIT 1;
```

And I get the very same error message.

**Comment by stachdude** [comment] 2017-03-30 21:59
Hi, any chance for some love for this issue ?

**Comment by poppyseedplehzr** [comment] 2017-03-30 22:09
@stachdude I'll try and kick this up my priority, sorry!  This is specific to Windows 7 yes? Have you been able to repro this any where else? It could be that building the thrift lib for Windows 7, and keeping a separate lib, might resolve the issue. I'll see if I can repro and fix later tonight

**Comment by poppyseedplehzr** [comment] 2017-04-02 20:35
@stachdude have you been able to repro this on master? I'm currently running osqueryd as SYSTEM on Windows 7 x64 Professional SP1 with a scheduled query of `select * from processes limit 1;` and getting no crashes. What version of Windows 7 are you running? Also what version of osquery? I'll keep trying to trigger the crash on my end, but if you have any thoughts of env that might be different that would be helpful

**Comment by stachdude** [comment] 2017-04-03 06:46
I'll do the tests today, and will get back with results asap.

**Comment by poppyseedplehzr** [comment] 2017-05-06 23:27
Hey @stachdude, any chance you were able to repro? I'm still not able to repro this on Win7 x64 pro with SP1, running as `osqueryd` and `osqueryi` it's running great. Let me know, I'll keep tweaking things to see if I can repro a crash.

**Comment by poppyseedplehzr** [comment] 2017-05-23 16:32
@stachdude any chance you could repro this for me? We recently bumped thrift to 0.10.0, and I'm wondering if this issue has gone away.

**Comment by poppyseedplehzr** [comment] 2017-05-25 05:08
@stachdude I'm going to go ahead and close this out, but please feel free to re-open if you can repro the issue. I'll be allocating more cycles in the coming weeks to Windows 7 support, and if this shows up again I'll re-open this issue to track fixes. Thanks!

**Closed by poppyseedplehzr** 2017-05-25 05:08 UTC
Labels: debt, triage, Windows
