### ISSUE TITLE
macOS Mojave disk_encryption table errors. 

### ISSUE THREAD

**Issue by groob** [facebook/osquery#4494] opened 2018-06-05 00:38 UTC
```
osquery> select * from disk_encryption;
E0604 20:33:26.270823 2336093056 disk_encryption.mm:259] Error calling isEncryptedVolume:encrypted:
E0604 20:33:26.272387 2336093056 disk_encryption.mm:259] Error calling isEncryptedVolume:encrypted:
E0604 20:33:26.273867 2336093056 disk_encryption.mm:259] Error calling isEncryptedVolume:encrypted:
E0604 20:33:26.275045 2336093056 disk_encryption.mm:259] Error calling isEncryptedVolume:encrypted:
I0604 20:33:26.369046 2336093056 virtual_table.cpp:291] Error casting encrypted () to INTEGER
I0604 20:33:26.369112 2336093056 virtual_table.cpp:291] Error casting encrypted () to INTEGER
I0604 20:33:26.369141 2336093056 virtual_table.cpp:291] Error casting encrypted () to INTEGER
I0604 20:33:26.369164 2336093056 virtual_table.cpp:291] Error casting encrypted () to INTEGER
+--------------+--------------------------------------+-----------+------+-----+--------------------------------------+
| name         | uuid                                 | encrypted | type | uid | user_uuid                            |
+--------------+--------------------------------------+-----------+------+-----+--------------------------------------+
| /dev/disk0   |                                      |           |      |     |                                      |
| /dev/disk0s1 | 9495DF6A-4DF3-4D91-8FCC-ADB783222849 |           |      |     |                                      |
| /dev/disk0s2 | 4F8335A5-6AC8-4DF9-940D-F6DD22AFB8E7 |           |      |     |                                      |
| /dev/disk1   | 7B08C779-2647-4B52-8D00-6D29A9889B93 |           |      |     |                                      |
| /dev/disk1s1 | 8E0F5F28-8C2C-464B-BEBE-F4B4878F87D1 | 0         |      | 501 | 594EEACB-379E-44E4-8C1A-A06DDCC002DA |
| /dev/disk1s2 | F483B99D-08F1-44B2-973D-A14DDA701E41 | 0         |      |     |                                      |
| /dev/disk1s3 | F335B91E-AE45-46D4-8F4F-1FF542437B48 | 0         |      |     |                                      |
| /dev/disk1s4 | 313AA767-6143-4F33-86CC-2E0F9E933D00 | 0         |      |     |                                      |
+--------------+--------------------------------------+-----------+------+-----+--------------------------------------+
```

**Comment by terracatta** [comment] 2018-06-05 11:49
Likely a dupe of #4479 which is actually a regression in 3.2.6 not a change in the API. @groob does 3.2.4 produce a correct result on 10.14?

**Comment by obelisk** [comment] 2018-06-05 16:51
I think this is a duplicate of 4479. Closing but reopen if I'm wrong.

**Closed by obelisk** 2018-06-05 16:51 UTC
