### ISSUE TITLE
Error casting uid () to BIGINT

### ISSUE THREAD

**Issue by danielpops** [facebook/osquery#2832] opened 2016-12-03 02:14 UTC
Sometimes on some hosts we see this error message:

`│I1202 18:00:43.554610  2659 virtual_table.cpp:273] Error casting uid () to BIGINT`

Here is the context in the output when running osqueryd --verbose:

```
I1202 18:03:30.601385  1241 scheduler.cpp:63] Executing scheduled query: ops_processes: SELECT DISTINCT name, uid, username, cmdline from processes JOIN users using(uid);
I1202 18:03:30.710222  1241 virtual_table.cpp:273] Error casting uid () to BIGINT

[996 more of these snipped]

I1202 18:03:30.829177  1241 virtual_table.cpp:273] Error casting uid () to BIGINT
I1202 18:03:30.829254  1241 virtual_table.cpp:273] Error casting uid () to BIGINT
I1202 18:03:30.849200  1241 scheduler.cpp:122] Found results for query: ops_processes
```

I was able to kinda repro this using osqueryi:

```
$ echo "SELECT * FROM processes where uid is NULL;" | osqueryi

+-------+------+------+---------+-------+-----+------+-----+-----+------+------+------+------+---------+------------+---------------+------------+-----------+-------------+------------+--------+--------+---------+------+
| pid   | name | path | cmdline | state | cwd | root | uid | gid | euid | egid | suid | sgid | on_disk | wired_size | resident_size | total_size | user_time | system_time | start_time | parent | pgroup | threads | nice |
+-------+------+------+---------+-------+-----+------+-----+-----+------+------+------+------+---------+------------+---------------+------------+-----------+-------------+------------+--------+--------+---------+------+
| 13603 |      |      |         |       |     |      |     |     |      |      |      |      | -1      | 0          |               |            |           |             |            |        |        |         |      |
| 13641 |      |      |         |       |     |      |     |     |      |      |      |      | -1      | 0          |               |            |           |             |            |        |        |         |      |
| 13710 |      |      |         |       |     |      |     |     |      |      |      |      | -1      | 0          |               |            |           |             |            |        |        |         |      |
| 13711 |      |      |         |       |     |      |     |     |      |      |      |      | -1      | 0          |               |            |           |             |            |        |        |         |      |
| 14320 |      |      |         |       |     |      |     |     |      |      |      |      | -1      | 0          |               |            |           |             |            |        |        |         |      |
| 14321 |      |      |         |       |     |      |     |     |      |      |      |      | -1      | 0          |               |            |           |             |            |        |        |         |      |
| 14322 |      |      |         |       |     |      |     |     |      |      |      |      | -1      | 0          |               |            |           |             |            |        |        |         |      |
+-------+------+------+---------+-------+-----+------+-----+-----+------+------+------+------+---------+------------+---------------+------------+-----------+-------------+------------+--------+--------+---------+------+
```

Is that expected to see such results from the processes table? Has anybody seen this before? Should we filter these records out?

**Comment by theopolis** [comment] 2016-12-03 02:29
What OS is this, and does running as a super user change the results? If Linux, are there namespaces/cgroups/containers involved? Does anything show up in /proc for those pids?

**Comment by danielpops** [comment] 2016-12-03 02:39
This is on `trusty`, and this is from running as super user. These are AWS hosts.

It was actually pretty difficult for me to capture that result with pids but no other details. I had to run the query several tens of times in quick succession before I was able to catch them, so I suspect i wouldn't have had a chance to check for their presence in /proc

**Comment by theopolis** [comment] 2016-12-03 07:00
That's really odd, I'm trying to reproduce by scripting it and not having any luck.

**Comment by theopolis** [comment] 2016-12-31 02:35
Is there anything that would be creating zombie processes? Can you give me the kernel version in use here?

**Comment by danielpops** [comment] 2017-01-03 19:20
I don't recall the exact host that I saw this occur on last, though, I have seen it across many hosts in our fleet. Next time I see this occur, I'll take note of the kernel version etc. 

As far as zombie processes go, we were seeing lots and lots of zombie processes coming from osquery itself. We were stuck on a very very old version of osquery (1.5.2!) until just a few weeks ago. Not sure if that has any relevance here or not. For what it's worth, there are many people that use these machines, so in theory it is possible that zombie processes might be being created here and there.

**Comment by theopolis** [comment] 2017-01-04 05:11
I can see where zombies from osquery can occur, looks like an artifact from the Windows integration: https://github.com/facebook/osquery/blob/master/osquery/core/posix/process_ops.cpp#L75

That will race against the child process handling the signal from `kill`, if the thread does not respond before osquery's watchdog `wait`s the child worker will remain zombied. Seems pretty high-pri to fix, we'll need to attempt that wait until the expected PID from the child is returned, or some timeout occurs.

//cc @PoppySeedPlehzr and @jedi22

**Comment by theopolis** [comment] 2017-06-16 04:16
There has been several clean ups to the `process_ops` abstraction. Any luck in tracking down another showing these error signs?

**Comment by danielpops** [comment] 2017-06-21 20:13
At the time that I reported this bug, I was running osqueryd in the foreground alot. Since then, it's been running as a service and I'm not actively monitoring for such log messages.

Havingsaidthat, it's been ~6 months now. We should probably be in a position to upgrade to the latest. If/when we do that, I can try running in the foreground for a few days and let you know if I still see those messages.

**Comment by theopolis** [comment] 2017-08-27 02:08
I'm going to cross my fingers that this was fixed with the refactors to `process_ops`. If there's still an error with 2.7.0 let's reopen and investigate!

**Closed by theopolis** 2017-08-27 02:08 UTC
Labels: bug, Linux, virtual tables
