### ISSUE TITLE
Compiler errors on Vagrant VMs

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#2949] opened 2017-01-28 21:32 UTC
While testing a feature on different operating systems, I spun up the `ubuntu16.04` VM and the `centos7.1` VM. While running `make deps` both of them ran into the following error (which I first noticed in #2685):

```
/usr/local/osquery/Cellar/glibc/2.19/bin/localedef
-i
en_US
-f
utf-8
en_US.utf-8

character map file `utf-8' not found: No such file or directory
no output file produced because warnings were issued
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall osquery/osquery-local/glibc`
```

On Ubuntu, I fixed this by running `sudo dpkg-reconfigure locales` and re-running `make deps`. On CentOS, I fixed this by running `export LANG=en_GB.UTF-8` and re-running `make deps`. Obviously a less future-proof solution on CentOS since I'm uncertain of the yum equivalent for `dpkg-reconfigure` :)

Deps completed successfully after that on both hosts.

On Ubuntu 16.04, the build failed with the following error:

```
Scanning dependencies of target example_extension
[ 78%] Building CXX object osquery/CMakeFiles/example_extension.dir/examples/example_extension.cpp.o
[ 78%] Linking CXX static library libosquery_testing.a
[ 78%] Linking CXX executable example_extension.ext
make[3]: warning:  Clock skew detected.  Your build may be incomplete.
/usr/local/osquery/bin/ld: /usr/local/osquery/Cellar/llvm/3.8.1_2/bin/../lib/LLVMgold.so: error loading plugin: /usr/local/osquery/legacy/lib/libm.so.6: symbol __get_cpu_features, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
clang-3.8: error: linker command failed with exit code 1 (use -v to see invocation)
osquery/CMakeFiles/example_extension.dir/build.make:109: recipe for target 'osquery/example_extension.ext' failed
make[3]: *** [osquery/example_extension.ext] Error 1
CMakeFiles/Makefile2:1240: recipe for target 'osquery/CMakeFiles/example_extension.dir/all' failed
make[2]: *** [osquery/CMakeFiles/example_extension.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[ 78%] Built target libosquery_testing
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
Makefile:53: recipe for target 'all' failed
make: *** [all] Error 2
```

On CentOS 7.1, the build failed with the following error:

```
[vagrant@localhost vagrant]$ make -j2
-- Found ccache /usr/local/osquery/bin/ccache
-- Using ccache to speed up compilation
-- The C compiler identification is Clang 3.8.1
-- The CXX compiler identification is Clang 3.8.1
-- Check for working C compiler: /usr/local/osquery/bin/clang
-- Check for working C compiler: /usr/local/osquery/bin/clang -- broken
CMake Error at /usr/local/osquery/Cellar/cmake/3.6.1_1/share/cmake/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler "/usr/local/osquery/bin/clang" is not able to compile a
  simple test program.
  It fails with the following output:
   Change Dir: /vagrant/build/centos7/CMakeFiles/CMakeTmp
  Run Build Command:"/usr/bin/gmake" "cmTC_ef521/fast"
  gmake[1]: Entering directory `/vagrant/build/centos7/CMakeFiles/CMakeTmp'
  gmake[1]: Warning: File `Makefile' has modification time 0.26 s in the
  future
  /usr/bin/gmake -f CMakeFiles/cmTC_ef521.dir/build.make
  CMakeFiles/cmTC_ef521.dir/build
  gmake[2]: Entering directory `/vagrant/build/centos7/CMakeFiles/CMakeTmp'
  gmake[2]: Warning: File `CMakeFiles/cmTC_ef521.dir/flags.make' has
  modification time 0.25 s in the future
  Building C object CMakeFiles/cmTC_ef521.dir/testCCompiler.c.o
  /usr/local/osquery/bin/clang -o CMakeFiles/cmTC_ef521.dir/testCCompiler.c.o
  -c /vagrant/build/centos7/CMakeFiles/CMakeTmp/testCCompiler.c
  Linking C executable cmTC_ef521
  /usr/local/osquery/Cellar/cmake/3.6.1_1/bin/cmake -E cmake_link_script
  CMakeFiles/cmTC_ef521.dir/link.txt --verbose=1
  /usr/local/osquery/bin/clang CMakeFiles/cmTC_ef521.dir/testCCompiler.c.o -o
  cmTC_ef521 -rdynamic
  /usr/local/osquery/bin/ld: cannot find crt1.o: No such file or directory
  /usr/local/osquery/bin/ld: cannot find crti.o: No such file or directory
  /usr/local/osquery/bin/ld: cannot find -lc
  /usr/local/osquery/bin/ld: cannot find crtn.o: No such file or directory
  clang-3.8: error: linker command failed with exit code 1 (use -v to see
  invocation)
  gmake[2]: *** [cmTC_ef521] Error 1
  gmake[2]: Leaving directory `/vagrant/build/centos7/CMakeFiles/CMakeTmp'
  gmake[1]: *** [cmTC_ef521/fast] Error 2
  gmake[1]: Leaving directory `/vagrant/build/centos7/CMakeFiles/CMakeTmp'
  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:266 (project)
-- Configuring incomplete, errors occurred!
See also "/vagrant/build/centos7/CMakeFiles/CMakeOutput.log".
See also "/vagrant/build/centos7/CMakeFiles/CMakeError.log".
make: *** [all] Error 1
```

I'm not sure if anyone else has experienced this recently with Vagrant VMs.

**Comment by theopolis** [comment] 2017-01-30 09:18
This is after a:
```
vagrant up centos7.1
cd /vagrant
sudo yum install git
make sysprep
make
```
Correct?

**Comment by marpaia** [comment] 2017-01-30 18:24
Err, no, sorry, I was running `make deps`, not `make sysprep`. After running `make sysprep`, both hosts fail with:

```
[ 76%] Linking CXX executable example_extension.ext
/usr/local/osquery/bin/ld: /usr/local/osquery/Cellar/llvm/3.8.1_2/bin/../lib/LLVMgold.so: error loading plugin: /usr/local/osquery/legacy/lib/libm.so.6: symbol __get_cpu_features, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
```

**Comment by theopolis** [comment] 2017-01-31 02:23
I'm having a lot of trouble reproducing these errors. If you don't mind providing as much detail as possible about your host setup that would be amazing. If you have another device that has completely different configuration, it would be helpful to test there too.

I've tested from 3 devices using centos7.1 and the AWS RHEL7.1 as test vagrant hosts.

**Comment by jedi22** [comment] 2017-03-09 23:09
@marpaia Are you still experiencing this build issue?

**Comment by marpaia** [comment] 2017-03-10 16:40
No, but that's because I was experiencing these issues when compiling on linux VMs on a Windows host and lately, I've been doing development on a macOS host again, so everything has been behaving as planned.

**Comment by poppyseedplehzr** [comment] 2017-03-10 20:03
@marpaia could you provide more details on the VM setup you have? VBox/Vmware? Anything special about your windows host? I haven't been able to repro this with a native Windows host and linux VMs either.

**Comment by theopolis** [comment] 2017-03-12 18:25
Let's close this out since it's a bit too snowflake. Feel free to update with progress is any is attempted.

**Closed by theopolis** 2017-03-12 18:25 UTC
Labels: build/test, triage
