### ISSUE TITLE
OS X 10.11.6: Missing hardware_* values from system_info

### ISSUE THREAD

**Issue by ryanbaer** [facebook/osquery#2301] opened 2016-07-30 22:10 UTC
Running the following command on 10.11.6:
`osqueryi --json "select hardware_model, hardware_serial, hardware_vendor, hardware_version from system_info"`

Results in the following:

```
[
  {
    "hardware_model": "",
    "hardware_serial": "",
    "hardware_vendor": "",
    "hardware_version": ""
  }
]
```

This is potentially correlated with the recent update / security patch on July 18, 2016 ([OS X El Capitan v10.11.6 and Security Update 2016-004](https://support.apple.com/en-us/HT206903)). Running the same query on another machine with 10.11.5 yielded the correct values.

**Comment by zwass** [comment] 2016-08-02 01:08
@ryanbaer I have that update installed and got correct results with `osquery 1.7.4`. I then updated to `osquery 1.8.2` and I still get the correct results.

Not sure what could be going on with yours. What version of osquery are you running?

**Comment by theopolis** [comment] 2016-08-10 03:38
Interesting, mine is working too!
```
$ osqueryi "select hardware_model, os_version.*, version from system_info join os_version join osquery_info"
+----------------+----------+-------+-------+-------+-------+---------+
| hardware_model | name     | major | minor | patch | build | version |
+----------------+----------+-------+-------+-------+-------+---------+
| MacBookPro11,1 | Mac OS X | 10    | 11    | 6     | 15G31 | 1.8.1   |
+----------------+----------+-------+-------+-------+-------+---------+
```

**Comment by ryanbaer** [comment] 2016-08-10 04:13
Strange. Mine and my coworker's both still return empty for those 4 fields.

@theopolis, we both ran your query (`osqueryi "select hardware_model, os_version.*, version from system_info join os_version join osquery_info"`)

His:
```
+----------------+----------+-------+-------+-------+-------+---------+
| hardware_model | name     | major | minor | patch | build | version |
+----------------+----------+-------+-------+-------+-------+---------+
|                | Mac OS X | 10    | 11    | 6     | 15G31 | 1.7.4   |
+----------------+----------+-------+-------+-------+-------+---------+
```
Mine:
```
+----------------+----------+-------+-------+-------+-------+---------+
| hardware_model | name     | major | minor | patch | build | version |
+----------------+----------+-------+-------+-------+-------+---------+
|                | Mac OS X | 10    | 11    | 6     | 15G31 | 1.8.0   |
+----------------+----------+-------+-------+-------+-------+---------+
```
Note that we both installed directly from the PKG on the website and not through homebrew.

Any other information I can give you all to help with this?

**Comment by theopolis** [comment] 2016-08-10 04:32
If you don't mind:
```
system_profiler SPHardwareDataType | grep -vE ".*(Serial|UUID).*"
```

And: `osqueryi -A smbios_tables`

I'm assuming `sudo osqueryi` doesn't work either?

**Comment by ryanbaer** [comment] 2016-08-10 22:15
`sudo osqueryi` did not change the response

```
$ system_profiler SPHardwareDataType | grep -vE ".*(Serial|UUID).*"
Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro12,1
      Processor Name: Intel Core i7
      Processor Speed: 3.1 GHz
      Number of Processors: 1
      Total Number of Cores: 2
      L2 Cache (per Core): 256 KB
      L3 Cache: 4 MB
      Memory: 16 GB
      Boot ROM Version: MBP121.0167.B17
      SMC Version (system): 2.28f7
```

```
$ osqueryi -A smbios_tables
+--------+------+------------------+--------+-------------+------+----------------------------------+
| number | type | description      | handle | header_size | size | md5                              |
+--------+------+------------------+--------+-------------+------+----------------------------------+
| 0      | 95   | Unknown          | 24397  | 83          | 85   | f318821d64928d2bf6025545f2b5f3f9 |
| 1      | 0    | BIOS Information | 0      | 0           | 2    | c4103f122d27677c9db144cae1394a66 |
| 2      | 0    | BIOS Information | 0      | 0           | 2    | c4103f122d27677c9db144cae1394a66 |
| 3      | 0    | BIOS Information | 0      | 0           | 2    | c4103f122d27677c9db144cae1394a66 |
| 4      | 0    | BIOS Information | 0      | 0           | 2    | c4103f122d27677c9db144cae1394a66 |
| 5      | 0    | BIOS Information | 0      | 0           | 2    | c4103f122d27677c9db144cae1394a66 |
| 6      | 0    | BIOS Information | 0      | 0           | 2    | c4103f122d27677c9db144cae1394a66 |

... (omitted for brevity) ...

| 760    | 0    | BIOS Information | 0      | 0           | 2    | c4103f122d27677c9db144cae1394a66 |
+--------+------+------------------+--------+-------------+------+----------------------------------+

**Comment by theopolis** [comment] 2016-08-10 23:55
Ok, so I'm guessing something is wrong with the SMBIOS parsing. I need to get my hands on a `MacBookPro12,1`.

**Comment by alcarithemad** [comment] 2016-09-23 05:02
I have a `MacBookPro12,1` and saw this issue while browsing yesterday. I tried to reproduce it then and was unable to, but I decided to check once more before posting.

I now see exactly the behavior described above. Fortunately, my original attempt was still in my terminal scrollback.

I didn't reboot between these command invocations.

Yesterday morning:

```
alcari@adler ~$ osqueryi "select hardware_model, os_version.*, version from system_info join os_version join osquery_info"
+----------------+----------+-------+-------+-------+-------+---------+
| hardware_model | name     | major | minor | patch | build | version |
+----------------+----------+-------+-------+-------+-------+---------+
| MacBookPro12,1 | Mac OS X | 10    | 11    | 6     | 15G31 | 1.7.3   |
+----------------+----------+-------+-------+-------+-------+---------+
alcari@adler ~$ system_profiler SPHardwareDataType | grep -vE ".*(Serial|UUID).*"
Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro12,1
      Processor Name: Intel Core i7
      Processor Speed: 3.1 GHz
      Number of Processors: 1
      Total Number of Cores: 2
      L2 Cache (per Core): 256 KB
      L3 Cache: 4 MB
      Memory: 16 GB
      Boot ROM Version: MBP121.0167.B17
      SMC Version (system): 2.28f7

alcari@adler ~$ osqueryi -A smbios_tables
+--------+------+----------------------------------+--------+-------------+------+----------------------------------+
| number | type | description                      | handle | header_size | size | md5                              |
+--------+------+----------------------------------+--------+-------------+------+----------------------------------+
| 0      | 7    | Cache Information                | 0      | 19          | 29   | b1e0e83cfea280ce981ebfc5b3b0425c |
| 1      | 7    | Cache Information                | 1      | 19          | 29   | 3730ce25126cc21325cf3a4d864a203e |
| 2      | 7    | Cache Information                | 2      | 19          | 29   | 3b0c18b4de55ef7a3c6aaf50584560de |
| 3      | 7    | Cache Information                | 3      | 19          | 29   | 7255a6269288363a9cc3c4ba6f824a72 |
| 4      | 4    | Processor Information            | 4      | 42          | 116  | 858c072e4ac7e8b4238f44677b688e23 |
| 5      | 0    | BIOS Information                 | 5      | 24          | 78   | 9beab0a7764706e1f0a74d9702517817 |
| 6      | 1    | System Information               | 6      | 27          | 85   | 3ede5ca120e68701c60c76ca3186fcb9 |
| 7      | 2    | Base Board or Module Information | 7      | 17          | 87   | 160e0a7924e9da661bdccef964b59563 |
| 8      | 3    | System Enclosure or Chassis      | 8      | 24          | 72   | 5288be7c1c388c68216d9f0ea515a54c |
| 9      | 8    | Port Connector Information       | 9      | 9           | 15   | f2359e7f96b024859cf90d9a2be713be |
| 10     | 8    | Port Connector Information       | 10     | 9           | 15   | 73edea5bd1802a3f13bdfa816a389077 |
| 11     | 8    | Port Connector Information       | 11     | 9           | 24   | d58fa68d285720f96925eccf827e4f25 |
| 12     | 8    | Port Connector Information       | 12     | 9           | 22   | 70f496269d43eab5406c8143c83d325c |
| 13     | 8    | Port Connector Information       | 13     | 9           | 21   | ecfd080200eba4f7faaefd480fc4b96c |
| 14     | 8    | Port Connector Information       | 14     | 9           | 18   | 397bf05f7845dd90809267c037b64546 |
| 15     | 41   | Onboard Devices Extended Info    | 15     | 11          | 40   | f2827637d65b193a42f5466b58b5193a |
| 16     | 41   | Onboard Devices Extended Info    | 16     | 11          | 31   | 3bce7810d3589fab77a9928fef28c237 |
| 17     | 41   | Onboard Devices Extended Info    | 17     | 11          | 17   | 2ccd9f6c1da43bbd08cfecf89f2a7f53 |
| 18     | 13   | BIOS Language Information        | 18     | 22          | 26   | beff0e3a46d64d5b0d46662e985035ca |
| 19     | 22   | Portable Battery                 | 19     | 26          | 28   | b6f08fd32c25f8253e259cf2839f5fc2 |
| 20     | 32   | System Boot Information          | 20     | 11          | 13   | e6cee55c18986d9e9a361224bf3b8a17 |
| 21     | 131  | OEM Processor Type               | 21     | 6           | 8    | 3fd0f761c0708db5247ffa1387926f7c |
| 22     | 133  | Unknown                          | 22     | 12          | 14   | 5ca2f9c959ebad00d3d25e69ae131571 |
| 23     | 128  | Unknown                          | 23     | 88          | 90   | 91ea3d2593eca9be2b85b1b709c84c57 |
| 24     | 134  | Unknown                          | 24     | 20          | 22   | b8848569300b91574d57569ecaf7787e |
| 25     | 16   | Physical Memory Array            | 25     | 23          | 25   | 488d0cbdffa98e67f519ded1e0887dac |
| 26     | 17   | Memory Device                    | 26     | 34          | 105  | d5f4b2ea1b5b9a330e4272ac162b1a45 |
| 27     | 130  | Memory SPD Data                  | 27     | 186         | 188  | d41e3288988c947ecef66fcd426bd28b |
| 28     | 17   | Memory Device                    | 28     | 34          | 105  | 3a702e085d2e40ff7dc96f1ad0142168 |
| 29     | 130  | Memory SPD Data                  | 29     | 186         | 188  | a8030e727494e7a4ff111195871b6bbd |
| 30     | 19   | Memory Array Mapped Address      | 30     | 31          | 33   | fc9aa80f786edd6f429be69e0f001496 |
| 31     | 127  | End-of-Table                     | 65279  | 4           | 4    | a6b53027f966a1216db1642a3482c8b8 |
+--------+------+----------------------------------+--------+-------------+------+----------------------------------+
```

Now:

```
alcari@adler ~$ osqueryi "select hardware_model, os_version.*, version from system_info join os_version join osquery_info"
+----------------+----------+-------+-------+-------+-------+---------+
| hardware_model | name     | major | minor | patch | build | version |
+----------------+----------+-------+-------+-------+-------+---------+
|                | Mac OS X | 10    | 11    | 6     | 15G31 | 1.7.3   |
+----------------+----------+-------+-------+-------+-------+---------+
alcari@adler ~$ osqueryi -A smbios_tables
+--------+------+------------------+--------+-------------+------+----------------------------------+
| number | type | description      | handle | header_size | size | md5                              |
+--------+------+------------------+--------+-------------+------+----------------------------------+
| 0      | 95   | Unknown          | 24397  | 83          | 85   | f318821d64928d2bf6025545f2b5f3f9 |
| 1      | 0    | BIOS Information | 0      | 0           | 2    | c4103f122d27677c9db144cae1394a66 |
| 2      | 0    | BIOS Information | 0      | 0           | 2    | c4103f122d27677c9db144cae1394a66 |
  ...
| 760    | 0    | BIOS Information | 0      | 0           | 2    | c4103f122d27677c9db144cae1394a66 |
+--------+------+------------------+--------+-------------+------+----------------------------------+
```

**Comment by theopolis** [comment] 2016-11-15 07:14
I haven't checked in on this data in a while, I still don't have access to a newer MacBook. If anyone has some time, do you mind checking the results with version `2.1.2`?

**Comment by zwass** [comment] 2016-11-15 16:58
I had to modify the query slightly to avoid an ambiguous column name error. Here is the result I get on a 2015 15" MBP:
```
osqueryi "select hardware_model, os_version.*, osquery_info.version from system_info join os_version join osquery_info"
+----------------+----------+---------+-------+-------+-------+---------+----------+---------------+----------+---------+
| hardware_model | name     | version | major | minor | patch | build   | platform | platform_like | codename | version |
+----------------+----------+---------+-------+-------+-------+---------+----------+---------------+----------+---------+
| MacBookPro11,4 | Mac OS X | 2.1.2   | 10    | 12    | 1     | 16B2555 | darwin   | darwin        |          | 2.1.2   |
+----------------+----------+---------+-------+-------+-------+---------+----------+---------------+----------+---------+
```

**Comment by theopolis** [comment] 2016-11-19 01:04
Maybe this is related to external hardware. Is anyone plugging in docking stations, Thunderbolt adapters, etc?

**Comment by theopolis** [comment] 2016-11-19 01:30
@ryanbaer, @alcarithemad, can you post or send me the output of:
```
sudo ioreg -w0 -c AppleSMBIOS -r
```

**Comment by rrb5068** [comment] 2016-11-19 01:39
Actually yes, I am definitely plugging into a Thunderbolt Dock.

By the way, since upgrading to Sierra I have not been able to reproduce this issue on my machine.

Here's the output of `sudo ioreg -w0 -c AppleSMBIOS -r`:
```
+-o AppleSMBIOS  <class AppleSMBIOS, id 0x100000137, registered, matched, active, busy 0 (0 ms), retain 5>
    {
      "IOProbeScore" = 0
      "CFBundleIdentifier" = "com.apple.driver.AppleSMBIOS"
      "IOMatchCategory" = "AppleSMBIOS"
      "IOClass" = "AppleSMBIOS"
      "IOProviderClass" = "IOPlatformDevice"
      "SMBIOS" = <071300000180012000200020002000000404074c312043616368650000071301000180012000200020002000000403074c312043616368650000071302000181010001000120002000000505074c322043616368650000071303000182010010001020002000000605084c332043616368650000042a04000103c602d4060300fffbebbf038b19001c0c480d412e010002000300040506020204fc00c6005533453100496e74656c28522920436f72706f726174696f6e00496e74656c28522920436f726528544d292069372d353535375520435055204020332e313047487a00200020002000000018050001020000037f8098010000000000810a0001ffff4170706c6520496e632e004d42503132312e38385a2e303136372e4231372e313630363233313732310030362f32332f323031360000011b06000102030481750451b68e6f56a3c4b243e192a44e0605064170706c6520496e632e004d6163426f6f6b50726f31322c3100312e3000433032524c305a32465648390020004d6163426f6f6b2050726f0000021107000102030405010608000a0000004170706c6520496e632e004d61632d45343343314332354434383830414436004d6163426f6f6b50726f31322c310043303236313635303133434751313031450020002000000318080001090203040303030300000000000000000000004170706c6520496e632e004d61632d4534334331433235443438383041443600433032524c305a32465648390020000008090900000001121055534230000008090a00000001121055534231000008090b000000011f1d417564696f204c696e6520496e000008090c0000000100ff5468756e646572626f6c74000008090d0001ff0000004d6963726f70686f6e65000008090e0001ff000000537065616b65720000290b0f0001830100000000496e746567726174656420566964656f20436f6e74726f6c6c65720000290b100001870100000000417a616c696120417564696f20436f6465630000290b1100018901000000005341544100000d161200010100000000000000000000000000000001656e0000161a1300000000000002000000000000000000000000000000000000200b14000000000000000000008306150006070000850c160002000000000000000000805817000300000036f503fc3fff03fc0200030000000000000099ffffffafff0000b0ffffffd4ff0000d7ffffffd9ff00000000000000000000000000000000000000000000000000000000000000000000000000000000000086141800322e323846303700000000000000000000001017190003030300008000feff02000000000000000000000011221a001900feff4000400000200d0001021880004b070304000500000000004b0744494d4d300042414e4b2030003078383041440030783030303030303030003078343833393433343334453445344534333443353434443443343135323244344535353434000082ba1b001a000000b0009120f103051a050a031101080900400578789050901150e090063c3c019000000000cafa000000a8000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080ad010000000000000000483943434e4e4e434c544d4c41522d4e5544000080ad0000000000000000000000000000000000000000000000000000000011221c001900feff4000400000200d0001021880004b070304000500000000004b0744494d4d300042414e4b2031003078383041440030783030303030303030003078343833393433343334453445344534333443353434443443343135323244344535353434000082ba1d001c000000b0009120f103051a050a031101080900400578789050901150e090063c3c019000000000cafa000000a8000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080ad010000000000000000483943434e4e4e434c544d4c41522d4e5544000080ad00000000000000000000000000000000000000000000000000000000131f1e00ffffffffffffffff1900000000000000000000ffffffff0300000000007f04fffe0000>
      "IONameMatch" = "bios"
      "IONameMatched" = "bios"
      "SMBIOS-EPS" = <5f534d5fbe1f0207bc000000000000005f444d495fa6480600d0fa8a200000>
    }
```

**Comment by theopolis** [comment] 2016-11-19 02:23
Cool! But also darn! I'm trying to capture that output on a failing system. My hypothesis is a dock-like device is adding something to SMBIOS that is causing a parsing error.

**Comment by theopolis** [comment] 2017-04-03 07:19
I guess we never found out what was causing these errors? If anyone finds a system they can reproduce on, please find me on the osquery Slack so we can quickly debug!

**Closed by theopolis** 2017-04-03 07:19 UTC
Labels: bug, El Cap, macOS, needs response
