### ISSUE TITLE
file table, check directory query predicate

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#817] opened 2015-03-03 22:22 UTC
Hey @jedi22, I think there's a regression in the file table, when listFilesInDirectory was moved into two functions. Now there `where directory =` only lists file inodes. Mind taking a look?

**Comment by jedi22** [comment] 2015-03-04 01:25
Looking in the file.cpp table, it barely accesses the public filesystem.h interface, in fact it only does for `lsperms`. So if this is a regression, I don't think it was caused by that. Should 
`select * from file where directory = '/'` return /usr, /bin etc?

**Comment by theopolis** [comment] 2015-03-04 02:43
Yeah, looks like we need to change that logic to emit the directories too!

**Comment by jedi22** [comment] 2015-03-04 19:05
#822

**Comment by jedi22** [comment] 2015-03-04 19:46
Merged
![blog_120906_08](https://cloud.githubusercontent.com/assets/2386877/6491725/1981a6a2-c264-11e4-9ca7-e3f2448d851e.png)

**Closed by jedi22** 2015-03-04 19:46 UTC
Labels: triage, virtual tables
