### ISSUE TITLE
packaging osquery for Debian: help for ongoing issues

### ISSUE THREAD

**Issue by sandrotosi** [facebook/osquery#2321] opened 2016-08-05 14:43 UTC
Hello,
several hours ago I sent a similar email to osquery@googlegroups.com, but i still dont see it published nor i received a moderation notification, so I'm writing here too, apologies for the cross-posting and feel free to close this issue if we can keep talking on google groups.

I'm working at packaging osquery for inclusion in Debian as an
official package, and I'm facing a few issues for which id like to ask
your help. I feel it might take a bit of back-and-forth to get them
all iron out, so let's keep this chat going ;)

you at debian we are weird so i had to change slightly the build
process (so we wont be able to run make deps) but i finally got to a
point were the code starts building.

i got the first real issue when "something" in the build process
started to MAKEFLAGS with the single letter "w", and that of course
messes up with make (it cant find a target named 'w' of course), so i
needed to get rid of $(MAKEFLAGS) from the all target in Makefile.
have you ever heard of that? but anyway that's minor and solved (more
or less).

what I'm stuck at now is the build of utils_amalgamation.cpp which
fails with this error:

```
cd /home/morph/deb/osquery-1.8.1/build/sid && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/morph/deb/osquery-1.8.1 /home/morph/deb/osquery-1.8.1/osquery /home/morph/deb/osquery-1.8.1/build/sid /home/morph/deb/osquery-1.8.1/build/sid/osquery /home/morph/deb/osquery-1.8.1/build/sid/osquery/CMakeFiles/osquery_amalgamation.dir/DependInfo.cmake --color=
Scanning dependencies of target osquery_amalgamation
make -f osquery/CMakeFiles/osquery_amalgamation.dir/build.make osquery/CMakeFiles/osquery_amalgamation.dir/build
[  8%] Generating ../generated/tables_utils/file.cpp
[  8%] Generating ../generated/tables_utils/hash.cpp
[  8%] Generating ../generated/tables_utils/osquery_events.cpp
[  8%] Generating ../generated/tables_utils/osquery_extensions.cpp
[  8%] Generating ../generated/tables_utils/osquery_flags.cpp
[  8%] Generating ../generated/tables_utils/osquery_info.cpp
[  8%] Generating ../generated/tables_utils/osquery_packs.cpp
[  8%] Generating ../generated/tables_utils/osquery_registry.cpp
[  8%] Generating ../generated/tables_utils/osquery_schedule.cpp
[  8%] Generating ../generated/tables_utils/time.cpp
[  8%] Generating ../generated/utils_amalgamation.cpp
[  8%] Building CXX object osquery/CMakeFiles/osquery_amalgamation.dir/__/generated/utils_amalgamation.cpp.o
cd /home/morph/deb/osquery-1.8.1/build/sid/osquery && /usr/bin/c++   -DBOOST_NETWORK_ENABLE_HTTPS -DBOOST_NO_CXX11_VARIADIC_TEMPLATES -DDEBIAN -DDEBIAN_BASED=1 -DDEBIAN_SID -DHAS_SSL_TXT_TLSV1_2 -DNDEBUG -DNO_SSL_TXT_SSLV3 -DOSQUERY_BUILD_DISTRO=sid -DOSQUERY_BUILD_PLATFORM=debian -DOSQUERY_BUILD_SDK_VERSION=1.0.0 -DOSQUERY_THRIFT="" -DOSQUERY_THRIFT_LIB=thrift -DOSQUERY_THRIFT_POINTER=boost -DOSQUERY_THRIFT_SERVER_LIB=thrift/server -DSTRIP_FLAG_HELP=1 -I/home/morph/deb/osquery-1.8.1/build/sid/generated/gen-cpp -I/home/morph/deb/osquery-1.8.1/include -I/home/morph/deb/osquery-1.8.1 -I/usr/local/include -I/home/morph/deb/osquery-1.8.1/third-party/sysroots/linux  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security     -std=c++11 -static -Wstrict-aliasing -Wno-missing-field-initializers -Wno-unused-local-typedef -Wno-unknown-warning-option -Wnon-virtual-dtor -Wchar-subscripts -Wpointer-arith -Woverloaded-virtual -Wformat -Wformat-security -Werror=format-security -Wabi-tag -fpermissive -fstack-protector-all -fPIE -fpie -fPIC -fpic -pipe -fdata-sections -ffunction-sections -Os -march=x86-64 -mno-avx -Wall -Wextra -Wno-unused-parameter -o CMakeFiles/osquery_amalgamation.dir/__/generated/utils_amalgamation.cpp.o -c /home/morph/deb/osquery-1.8.1/build/sid/generated/utils_amalgamation.cpp
c++: error: /home/morph/deb/osquery-1.8.1/build/sid/generated/utils_amalgamation.cpp: No such file or directory
c++: fatal error: no input files
compilation terminated.
osquery/CMakeFiles/osquery_amalgamation.dir/build.make:162: recipe for target 'osquery/CMakeFiles/osquery_amalgamation.dir/__/generated/utils_amalgamation.cpp.o' failed
make[5]: *** [osquery/CMakeFiles/osquery_amalgamation.dir/__/generated/utils_amalgamation.cpp.o] Error 1
CMakeFiles/Makefile2:563: recipe for target 'osquery/CMakeFiles/osquery_amalgamation.dir/all' failed
make[4]: *** [osquery/CMakeFiles/osquery_amalgamation.dir/all] Error 2
```

do you know how to fix it?

Thanks a ton in advance and for your patience with our processes

Regards,
Sandro

**Comment by theopolis** [comment] 2016-08-08 00:39
Hi Sando! Sorry for the Google Groups inconvenience, no one moderates the group-- I'll look into closing it down.

I think you're experiencing a CMake targets dependency issue (more like a race condition). The expected source is not yet generated. We meta program out the table specifications and use a Python script to generate C++ code and an amalgamated single source to speed up compiling.

**Comment by sandrotosi** [comment] 2016-08-08 07:40
thanks @theopolis for your reply! do you have any hints on how to fix that dependency/race and let the build continue?

**Comment by theopolis** [comment] 2016-08-08 22:34
Let me dig into this tonight and shoot for a fix. I am not sure where the problem in the CMake logic is exactly so I cannot suggest a bypass ;)

**Comment by theopolis** [comment] 2016-08-10 04:08
Alright, as an aside, check out the `BUILD_LINK_SHARED ` environment variable. It will help your build environment prefer dynamic links over static libraries: http://osquery.readthedocs.io/en/stable/development/building/#debug-builds-formatting-and-more

I'm trying to force CMake to reproduce this dependency error now.

**Comment by theopolis** [comment] 2016-08-10 15:41
Hey @sandrotosi, I'm failing to find a critical section in the CMake logic, or the dependencies it sets for the `utils_amalgamation` target. Does your build setup allow for some debugging? Can we see if:
```
/home/morph/deb/osquery-1.8.1/build/sid/generated/utils_amalgamation.cpp
```
exists?

**Comment by sandrotosi** [comment] 2016-08-10 15:54
heh the error is `/home/morph/deb/osquery-1.8.1/build/sid/generated/utils_amalgamation.cpp: No such file or directory` so no, it doesnt exit :) i just make sure of it by reattempting a build, and it stops at the same place with the same error of my original post; i also ran a `find . -name "*utils_amalgamation*"` and it returns no file

**Comment by theopolis** [comment] 2016-08-10 16:07
Ok, and does a subsequent build get farther?

How I'm testing:
```
$ vagrant up debian8
$ vagrant ssh debian8
(vagrant) $ cd /vagrant
(vagrant) $ make deps
(vagrant) $ make
```

**Comment by sandrotosi** [comment] 2016-08-10 16:15
just tested and it failes at the same point, but the debian build process cleans up the built artifacts between builds, so that's not a surprise (for me at least :) )

in trying to make osquery adhere to the debian policy i needed to make some changes to its build mechanism (for example, i cant run `make dep`), so it's better if i publish what i did somewhere, but i'm afraid it will have to wait until tomorrow morning (EU time), sorry about that!

**Comment by theopolis** [comment] 2016-08-10 16:18
```
$ cmake --version
cmake version 3.6.0
$ python --version
Python 2.7.9
$ /usr/local/osquery/bin/python ./tools/codegen/gentable.py ./specs/uptime.table /tmp/uptime.cpp
$ echo $?
0
```

I totally understand the inability to use `make deps`, it does not fit with package management by design. Can you check that the python module requirements are satisfied?
```
$ cat requirements.txt 
Jinja2
argparse
thrift

# The pip / setup tools for Windows will not include psutil
# Needed for integration tests
psutil
pexpect

# For building the wiki
mkdocs
```

**Comment by sandrotosi** [comment] 2016-08-12 12:22
i added those modules (argparse is in the standard library for 2.7) that were indeed missing and your example command was failing due to a missing jinja2, but the whole building process still stops at the same point with `c++: error: /home/morph/deb/osquery-1.8.1/build/sid/generated/utils_amalgamation.cpp: No such file or directory`

**Comment by sandrotosi** [comment] 2016-08-12 13:56
I've pushed my (extremely work in progress) packaging at https://anonscm.debian.org/cgit/users/morph/osquery.git/ , you might want to have a look in particular to https://anonscm.debian.org/cgit/users/morph/osquery.git/tree/debian/control#n5 (line 5) for the packages installed during the build process and https://anonscm.debian.org/cgit/users/morph/osquery.git/tree/debian/patches for the patches i'm currently applying (the order is in the series file)

**Comment by theopolis** [comment] 2016-08-13 00:12
Ok, will take a look this weekend, thanks for the scripts/logs @sandrotosi!

**Comment by sandrotosi** [comment] 2016-08-19 08:33
gentle reminder to let me know if i can help you in any way with this

**Comment by theopolis** [comment] 2016-08-24 16:42
I could use some help, I looked into the dependency order for the CMake `add_custom_target`s and couldn't find anything obviously wrong. There may be a secondary python command thats failing to generate the `utils_amalgamation.cpp` file.

**Comment by sandrotosi** [comment] 2016-08-25 15:09
sure! do you know how to enable additional debugging output? i tried to add https://anonscm.debian.org/cgit/users/morph/osquery.git/tree/debian/patches/verbose-building.patch but maybe there some other options to add? or can even run commands by hand if you know what they are

**Comment by juju4** [comment] 2017-06-24 19:31
My current testing seems to show osquery never start correctly on first boot.
```
Jun 24 19:17:27 00ef7f02ad6c systemd[1]: Starting The osquery Daemon...
Jun 24 19:17:27 00ef7f02ad6c systemd[1]: Started The osquery Daemon.
Jun 24 19:17:27 00ef7f02ad6c osqueryd[1560]: osqueryd started [version=2.4.0]
Jun 24 19:17:27 00ef7f02ad6c osqueryd[1560]: I0624 19:17:27.536849  1566 rocksdb.cpp:222] Rocksdb open failed (5:0) IO error: lock /var/osquery/osquery.db/LOCK: Resource temporarily unavailable
Jun 24 19:17:27 00ef7f02ad6c osqueryd[1560]: E0624 19:17:27.536926  1566 init.cpp:574] [Ref #1629] osqueryd initialize failed: Could not initialize database
```
https://travis-ci.org/juju4/ansible-osquery/jobs/246615342#L2436

Manual restart after is fine.
Not sure why it happens on debian and not ubuntu or other systems.
Also not caught latest release as current is 2.5.1

**Comment by theopolis** [comment] 2017-06-24 23:18
> Also not caught latest release as current is 2.5.1

In your output it says `version=2.4.0` is this a red herring? Should that be `2.5.0`?

**Comment by kmaja** [comment] 2017-06-30 10:18
Hey, I have the same error, do you find any solution?

**Comment by theopolis** [comment] 2017-06-30 16:25
There are two errors in this issue: (1) a CMake problem that prevents Debian packaging, (2) an untriaged report of RocksDB not starting on first boot.

**Comment by spasam** [comment] 2017-09-23 23:33
@theopolis Based on recent vagrant based tests this should work now. Can be closed.

**Comment by theopolis** [comment] 2017-09-24 00:15
Ok, since this is fairly outdated I'll take your word @spasam. There may nuances introduced into the build when trying to build within Debian's package build environment, causing it to fail.

**Closed by theopolis** 2017-09-24 00:15 UTC
Labels: build/test, Linux, packaging, triage
