### ISSUE TITLE
CentOS 6.0 Stable Build Errors

### ISSUE THREAD

**Issue by maus-** [facebook/osquery#789] opened 2015-02-24 00:08 UTC
While running this config https://gist.github.com/maus-/aaba8b03f7ea0ac6c11b with the CentOS 6.0 stable build. No results ever populate using osqueryd however I get flooded with W0223 23:48:39.519681  5043 watcher.cpp:130] osqueryd worker respawning too quickly 

Seems to be working fine with the latest build. Not sure whats up with that.

**Comment by theopolis** [comment] 2015-02-24 04:59
Wow, excellent find!

I think this is the root cause: https://github.com/facebook/osquery/compare/1.4.1...master#diff-65a2f4d5bc14ba875ea7ec42a40f14b0R147

**Comment by marpaia** [comment] 2015-02-24 21:25
Labeling this as wont fix since the path forward is to cut a new release.

**Closed** 2015-02-24 21:26 UTC
Labels: bug, deployment infrastructure, wont fix
