### ISSUE TITLE
linux: Audit redesign merge criteria

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#3871] opened 2017-10-22 09:56 UTC
From what I can see by running the daemon:
- The ^D event is not handled quickly. The daemon or shell still takes a few moments before stopping. Is there any way to make this respond quicker?
- The implementation is still taking way more resources at idle that master. After a minute the redesign is +20 seconds of system CPU while master is around 4 or 6.

**Comment by Centurion89** [comment] 2017-10-24 00:59
@theopolis do you have any metrics for this running under load or stress test results? Happy to provide metrics across a handful of OS's if that would be helpful.

**Comment by alessandrogario** [comment] 2017-11-20 10:12
Hello Teddy!

I've made some small changes that may help us improve responsiveness when we terminate the process and reduce CPU usage during idle time:
 * Terminate message acquisition earlier if being interrupted.
 * Abort message queue processing when being interrupted.
 * Lower the getEvents() timeout.
 * Increase the poll() timeout in acquireMessages().

The following are the tests I've performed after the changes:
## audit-redesign branch
### Command:
```
time ./osqueryd --disable_events=false --audit_debug \
--verbose --disable_audit=false --audit_force_reconfigure=true \
--audit_allow_config=true --allow_unsafe --disable_watchdog
```
### Results
 * 0.03s user 0.02s system 0% cpu 1:02.62 total
 * 0.04s user 0.02s system 0% cpu 1:02.64 total
## master branch
### Command:
```
time ./osqueryd --disable_events=false --audit_debug \
--verbose --disable_audit=false \
--audit_allow_config=true --allow_unsafe --disable_watchdog
```
### Results
 * 0.06s user 0.04s system 0% cpu 1:01.39 total
 * 0.05s user 0.04s system 0% cpu 1:01.39 total

The branch is located here: https://github.com/trailofbits/osquery-pr/tree/audit-redesign
I have had to rebase on master though, how can we submit the PR?

Thanks for your help!

**Comment by theopolis** [comment] 2017-12-11 03:46
Sorry for not updating sooner, I am retesting this branch now!

**Comment by theopolis** [comment] 2017-12-11 04:05
The performance of this branch is nice. There's an odd experience I have when testing, if I start `osqueryi`: 
```
sudo ./build/linux/osquery/osqueryi --nodisable_events --nodisable_audit --audit_allow_config --audit_persist --audit_allow_sockets --extensions_socket /tmp/audit_test --verbose
```

It takes about 60s for events to show up, and then another 60s before events between that period are populated. If this is a delay we need to deal with, OK, but it's different than the current UX.

There are other UX changes we should consider making to this branch to make the changes from master to this redesign simpler.
- The `user_events` table should be on by default if audit is used. That means that `socket_events` is the only additional opt-in after configuring osquery to use audit.
- The FIM events should go into the existing `process_file_events` table. The new table/schema added here should be removed. If there are new columns absolutely needed let's append them to the `process_file_events` table.
- The VERBOSE/INFO/WARNING messages should not use '...` or other types of punctuation and double check that no log lines are multiple-sentences, this is mostly a nitpick though.

**Comment by theopolis** [comment] 2017-12-11 04:07
I am seeing a LOT of:

````
I1210 20:05:51.554564  8781 socket_events.cpp:161] Invalid saddr field in AUDIT_SOCKADDR: "100000000000000000000000"
I1210 20:05:51.554569  8781 socket_events.cpp:161] Invalid saddr field in AUDIT_SOCKADDR: "100000000000000000000000"
I1210 20:05:51.554574  8781 socket_events.cpp:161] Invalid saddr field in AUDIT_SOCKADDR: "100000000000000000000000"
I1210 20:05:51.554577  8781 socket_events.cpp:161] Invalid saddr field in AUDIT_SOCKADDR: "100000000000000000000000"
I1210 20:05:51.554580  8781 socket_events.cpp:161] Invalid saddr field in AUDIT_SOCKADDR: "100000000000000000000000"
I1210 20:05:51.554584  8781 socket_events.cpp:161] Invalid saddr field in AUDIT_SOCKADDR: "100000000000000000000000"
I1210 20:05:51.554608  8781 socket_events.cpp:161] Invalid saddr field in AUDIT_SOCKADDR: "100000000000000000000000"
I1210 20:05:51.554613  8781 socket_events.cpp:161] Invalid saddr field in AUDIT_SOCKADDR: "100000000000000000000000"
I1210 20:05:51.554617  8781 socket_events.cpp:161] Invalid saddr field in AUDIT_SOCKADDR: "100000000000000000000000"
I1210 20:05:51.554625  8781 socket_events.cpp:161] Invalid saddr field in AUDIT_SOCKADDR: "100000000000000000000000"
I1210 20:05:51.554630  8781 socket_events.cpp:161] Invalid saddr field in AUDIT_SOCKADDR: "100000000000000000000000"
I1210 20:05:51.554636  8781 socket_events.cpp:161] Invalid saddr field in AUDIT_SOCKADDR: "100000000000000000000000"
```

Do you mind double checking that log line? There are situations where the socket you're inspecting does not intend for you to parse that address. If this isn't an error, like, if the line was for a UNIX socket, then let's not flood the screen in verbose mode (or not verbose mode).

**Comment by theopolis** [comment] 2017-12-11 04:13
Also, this is how I run some stress tests:
```
./tools/analysis/system_stress.py -n 11 -i lo
```

You can compare the time-to-complete (in seconds) for this branch, master, and without anything audit-related running. This measures the aggregate responsiveness indirectly for the system too. AKA subjectively, longer times mean the system is prone to locking up. Anything >22s will be absolutely noticeable.

The compare the impact osquery had:
```
> select p.pid, name, user_time, system_time, resident_size from processes p, osquery_info where p.pid = osquery_info.pid;
```

And compare the number of events osquery processed:
```
> select count(1) from process_events;
```

**Comment by alessandrogario** [comment] 2017-12-11 16:57
Hello Teddy!

It shouldn't take that long to acquire the audit handle on a clean start; I have noticed that once you acquire it and release it several times, then it may take a while for a program to be able to re-acquire it again (in my experience, it's worse on CentOS 6 compared to more recent kernel versions). I have more strict error checking in my branch in some places, and this is one of them (so maybe it's caused by this). It should show some more output about this if you use --audit_debug=true

I'll now look into the socket_events issue.

Thanks for taking the time to test this!

**Comment by clong** [comment] 2018-01-17 21:29
@theopolis I think we're probably good to close this issue

**Closed** 2018-01-19 15:51 UTC
Labels: Linux, process auditing
