### ISSUE TITLE
Environment variable `OSQUERY_DEPS` (used to control dependencies location) is not respected everywhere

### ISSUE THREAD

**Issue by nbigaouette-eai** [facebook/osquery#3373] opened 2017-06-01 18:51 UTC
I am attempting to build (not run) osquery on a macOS machine where I do not have root access. As such, I am using the `OSQUERY_DEPS` environment to point to a local directory where osquery's version of homebrew will be installed.

This works for the compilation but the `make test`, `make package` and `make packages` targets are not respecting this path and seems to have harcoded `/usr/local/osqery`.

Before I dig in and identify those places, am I properly expecting those targets to respect a custom `OSQUERY_DEPS`?

**Comment by theopolis** [comment] 2017-06-02 03:34
Can you try: 
```
OSQUERY_DEPS=/tmp/build make build_deps
```

Then a few hours later:
```
OSQUERY_DEPS=/tmp/build make
```

I think the issue is some of the tools included with the dependencies have their paths hardcoded to `/usr/local/osquery` (their prefix used during their builds). Our dependency build is not smart enough to try to rebuild when this home is different. :)

**Comment by nbigaouette-eai** [comment] 2017-06-02 14:28
I did try to rebuild the dependencies, and yes it does fix the issue. It's too long though ;)

I wander if the pre-built packages could respect `OSQUERY_DEPS`? Is that even possible? I'll take a look.

**Comment by nbigaouette-eai** [comment] 2017-06-02 19:58
Well, I can't source rebuild the deps anymore:
```
[+] brew package osquery/osquery-local/libmagic installing new version: 5.29_101
==> Installing libmagic from osquery/osquery-local
==> Downloading https://fossies.org/linux/misc/file-5.29.tar.gz

curl: (22) The requested URL returned error: 410 Gone
Error: Failed to download resource "libmagic"
Download failed: https://fossies.org/linux/misc/file-5.29.tar.gz
make[1]: *** [deps] Error 1
```

:S

**Comment by theopolis** [comment] 2017-06-03 04:00
It's totally too long ;) I'd love some help here, this is the best solution we could come up with. The issue, IIRC, here is the `:skip_any_relocation` added to the `bottle` DSO: https://github.com/facebook/osquery/blob/master/tools/provision/formula/python.rb#L13

If we remove that `brew` will detect you're installing into a new location and try to change those hardcoded paths. Some of the tools, like `python`, cannot be relocated easily and will force a reinstall, which would be awesome in this case (only rebuild those that need to be rebuilt). Initially this caused issues since we wanted to provide a 100%-from-bottle-to-default-deps-dir experience where no dependency compiling was needed. And some of the tools we install from `homebrew-core` would resist our customized destination dir and try to recompile. I haven't tested this experience in a long time, it's worth revisiting.

If you're setting up some build infrastructure you can re-bottle `python` using:
```
./tools/provision.sh bottle osquery/osquery-local/python
```
That will update the hashes in the embedded formula. The output tarball will be in `$OSQUERY_DEPS/` and you can place that in `$OSQUERY_DEPS/.cache` to skip an attempt to download. It's a bit messy :(

**Comment by nbigaouette-eai** [comment] 2017-06-07 20:43
For reference, here's the error I get with Python after having exported `OSQUERY_DEPS=${HOME}/osquery_deps_dir`:

```
[+] upgrading pip and installing python dependencies
Traceback (most recent call last):
  File "/Users/nbigaouette/osquery_deps_dir/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3081, in _call_aside
    f(*args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 658, in _build_master
    ws.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 959, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 846, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pip==8.1.2' distribution was not found and is required by the application
make: *** [deps] Error 1
```

**Closed** 2017-06-16 02:31 UTC
Labels: dependencies, macOS, needs response, triage
