### ISSUE TITLE
RPMDB Corruption causes rpm_packages query to fail to complete cleanly.

### ISSUE THREAD

**Issue by dreamlibrarian** [facebook/osquery#2632] opened 2016-10-17 16:52 UTC
Creating a new issue to rescope to _actual_ problems as opposed to dirty test environment problems - history in #2623.

Given a host with RPMDB corruption, querying against the rpm_packages table within osqueryd results in a hang after some number of iterations.

Using Doorman, the query results never reach the server.  Once the 'rocksdb.cpp:134' warning occurs, osqueryd goes nonresponsive for >=10 minutes. At 10 minutes I restarted osqueryd, which appeared to result in rocksdb corruption. Deleting the rocksdb directory and restarting allowed me to resume normal business.... until the next hang due to this RPM query failing.

Unfortunately, I've cleaned up the corruption in order to resolve #2623 as less horrifying than I'd feared, so I'm no longer reproducing.

Oct 13 11:38:42 localhost osqueryd[82437]: I1013 11:38:42.262019 82539 scheduler.cpp:63] Executing scheduled query: Get RPMs.: select \* from rpm_packages
Oct 13 11:38:42 localhost osqueryd[82437]: error: db6 error(-30969) from dbenv->open: BDB0091 DB_VERSION_MISMATCH: Database environment version mismatch
Oct 13 11:38:42 localhost osqueryd[82437]: error: cannot open Packages index using db6 -  (-30969)
Oct 13 11:38:42 localhost osqueryd[82437]: error: cannot open Packages database in
Oct 13 11:38:42 localhost osqueryd[82437]: error: db6 error(-30969) from dbenv->open: BDB0091 DB_VERSION_MISMATCH: Database environment version mismatch
Oct 13 11:38:42 localhost osqueryd[82437]: error: cannot open Packages index using db6 -  (-30969)
Oct 13 11:38:42 localhost osqueryd[82437]: error: cannot open Packages database in
Oct 13 11:39:17 localhost osqueryd[82437]: I1013 11:39:17.205925 82529 tls.cpp:205] TLS/HTTPS POST request to URI: https://doorman:443/config
Oct 13 11:39:17 localhost osqueryd[82437]: I1013 11:39:17.358981 82538 tls.cpp:205] TLS/HTTPS POST request to URI: https://doorman:443/distri
buted/read
Oct 13 11:39:17 localhost osqueryd[82437]: I1013 11:39:17.361577 82532 tls.cpp:205] TLS/HTTPS POST request to URI: https://doorman:443/log
Oct 13 11:39:36 localhost osqueryd[82437]: I1013 11:39:36.274595 82539 scheduler.cpp:63] Executing scheduled query: Get RPMs.: select \* from rpm_packages
Oct 13 11:39:36 localhost osqueryd[82437]: I1013 11:39:36.734776 82539 rpm_packages.cpp:50] Could not get RPM header flag.
Oct 13 11:39:36 localhost osqueryd[82437]: I1013 11:39:36.737107 82539 rpm_packages.cpp:50] Could not get RPM header flag.
Oct 13 11:39:36 localhost osqueryd[82437]: I1013 11:39:36.738487 82539 rpm_packages.cpp:50] Could not get RPM header flag.
Oct 13 11:39:36 localhost osqueryd[82437]: I1013 11:39:36.739590 82539 rpm_packages.cpp:50] Could not get RPM header flag.
Oct 13 11:39:36 localhost osqueryd[82437]: I1013 11:39:36.740705 82539 rpm_packages.cpp:50] Could not get RPM header flag.
Oct 13 11:39:36 localhost osqueryd[82437]: I1013 11:39:36.741863 82539 rpm_packages.cpp:50] Could not get RPM header flag.
Oct 13 11:39:36 localhost osqueryd[82437]: I1013 11:39:36.742985 82539 rpm_packages.cpp:50] Could not get RPM header flag.
Oct 13 11:39:36 localhost osqueryd[82437]: I1013 11:39:36.744211 82539 rpm_packages.cpp:50] Could not get RPM header flag.
Oct 13 11:39:36 localhost osqueryd[82437]: I1013 11:39:36.745234 82539 rpm_packages.cpp:50] Could not get RPM header flag.
Oct 13 11:39:36 localhost osqueryd[82437]: I1013 11:39:36.746378 82539 rpm_packages.cpp:50] Could not get RPM header flag.
Oct 13 11:39:36 localhost osqueryd[82437]: I1013 11:39:36.747520 82539 rpm_packages.cpp:50] Could not get RPM header flag.
Oct 13 11:39:36 localhost osqueryd[82437]: I1013 11:39:36.748648 82539 rpm_packages.cpp:50] Could not get RPM header flag.
Oct 13 11:39:36 localhost osqueryd[82437]: I1013 11:39:36.749667 82539 rpm_packages.cpp:50] Could not get RPM header flag.
Oct 13 11:39:38 localhost osqueryd[82437]: I1013 11:39:38.242105 82539 scheduler.cpp:122] Found results for query: Get RPMs.
Oct 13 11:39:39 localhost osqueryd[82437]: I1013 11:39:39.482309 82445 rocksdb.cpp:134] RocksDB: [WARN] [events] Increasing compaction threads because we have 8 level-0 files

**Comment by theopolis** [comment] 2016-10-18 04:49
@dreamlibrarian, I'm trying to understand what we can do to help with situations like these.

Can you help me understand how I can reproduce, or identify the error? Here's how I understand the situation:

1. You attempt to query `rpm_packages` every 10 minutes.
2. No results are returned from the query because the `rpmdb` has been corrupted by aliens.
3. No results are sent to RocksDB because none were found.
4. No logs are sent because there are no results?

The `WARN` you see from RocksDB is ok. That does not indicate an error, or a situation where data would have been corrupted. If there was corruption of RocksDB content, perhaps it's related to the original aliens issue that had corrupted your `RPMDB`?

My understanding may be incorrect, I see `Found results for query` in your output. What is your `--logger_tls_period` set to? This is the number of seconds in between sending logs, so don't expect another `TLS/HTTPS POST` message until you've waited that long.

**Comment by dreamlibrarian** [comment] 2016-10-18 20:59
I have logger_tls_period set to 120, so much faster than 10m. I had the dist query period set to 60 and --verbose was on, and the osqueryd was just... _silent_.

osqueryd did, as you note, log that it got results for the query on the local side; those results were never delivered to doorman, which confused me. Other tables results did arrive... at least until the db corruption started ruining my day.

Perhaps of note, after resolving my rpmdb corruption by blowing away __db.* in /var/lib/rpm and running 'rpm --rebuilddb',  it was corrupt again within a few hours. This starts to look like the problems we used to have with Puppet when it was using raw rpm lib access and fighting with yum; that fun ended with puppet abandoning using raw rpm libraries entirely, so let's hope it's not. Disabling puppet (which also wakes up and does regular rpm queries) kept me from getting corrupted again again, so I'm faintly wondering if there's a locking fight underway.  Haven't isolated it tho.

**Comment by theopolis** [comment] 2016-10-23 00:01
If you have time @dreamlibrarian, can you build osquery from master and see if my recent changes help?

**Comment by theopolis** [comment] 2016-11-01 02:24
This should be fixed with version 2.1.0+. Please let me know if you continue to see issues!

**Closed by theopolis** 2016-11-01 02:24 UTC
Labels: bug, Linux, needs response, triage, virtual tables
