### ISSUE TITLE
profile.py: ValueError: Invalid control character at: line 114 column 336 (char 5442)

### ISSUE THREAD

**Issue by juju4** [facebook/osquery#2892] opened 2017-01-03 12:30 UTC
Hello,

tested profiling tool as recommended in docs but not working

```
# ./tools/analysis/profile.py --config /etc/osquery/osquery.conf --shell /usr/bin/osqueryi --count 1 --rounds 4 --verbose 
Traceback (most recent call last):
  File "./tools/analysis/profile.py", line 341, in <module>
    queries = utils.queries_from_config(args.config)
  File "/tmp/osquery/tools/analysis/../tests/utils.py", line 97, in queries_from_config
    packqueries = json.loads(packcontent)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 114 column 336 (char 5442)
```

Tested on Ubuntu xenial and Macos 10.11.6 with latest osquery package and profile.py from github.
osquery.conf default with packs enabled

**Comment by fuzzball5000** [comment] 2017-01-03 12:36
Looks like Osquery is unable to parse your config json, can you post it here please?

**Comment by juju4** [comment] 2017-01-03 13:34
I copied it from repo (./tools/deployment/osquery.example.conf) so unless recent changes. but 2 eyes better than one

```
# cat /etc/osquery/osquery.conf
{
  // Configure the daemon below:
  "options": {
    // Select the osquery config plugin.
    "config_plugin": "filesystem",

    // Select the osquery logging plugin.
    "logger_plugin": "filesystem",

    // The log directory stores info, warning, and errors.
    // If the daemon uses the 'filesystem' logging retriever then the log_dir
    // will also contain the query results.
    //"logger_path": "/var/log/osquery",

    // Set 'disable_logging' to true to prevent writing any info, warning, error
    // logs. If a logging plugin is selected it will still write query results.
    //"disable_logging": "false",

    // Query differential results are logged as change-events to assist log                                                                                                                       // aggregation operations like searching and transactons.                                                                                                                                     // Set 'log_results_events' to log differentials as transactions.                                                                                                                             //"log_result_events": "true",

    // Splay the scheduled interval for queries.                                                                                                                                                  // This is very helpful to prevent system performance impact when scheduling
    // large numbers of queries that run a smaller or similar intervals.
    //"schedule_splay_percent": "10",                                                                                                                                                          
    // Write the pid of the osqueryd process to a pidfile/mutex.
    //"pidfile": "/var/osquery/osquery.pidfile",
    
    // Clear events from the osquery backing store after a number of seconds.
    "events_expiry": "3600",
    
    // A filesystem path for disk-based backing storage used for events and
    // and query results differentials. See also 'use_in_memory_database'.
    //"database_path": "/var/osquery/osquery.db",
    
    // Comma-delimited list of table names to be disabled.
    // This allows osquery to be launched without certain tables.
    //"disable_tables": "foo_bar,time",
    
    // Enable debug or verbose debug output when logging.                                                                                                                                         "verbose": "false",
    
    // The number of threads for concurrent query schedule execution.
    "worker_threads": "2",
    
    // Enable schedule profiling, this will fill in averages and totals for
    // system/user CPU time and memory for every query in the schedule.
    // Add a query: "select * from osquery_schedule" to record the performances.
    "enable_monitor": "true"
  },

  // Define a schedule of queries:
  "schedule": {
    // This is a simple example query that outputs basic system information.
    "system_info": {
      // The exact query to run.
      "query": "SELECT hostname, cpu_brand, physical_memory FROM system_info;",
      // The interval in seconds to run this query, not an exact interval.
      "interval": 3600
    }
  },

  // Add default osquery packs or install your own.
  //                                                                                                                                                                                            // There are several 'default' packs installed with 'make install' or via                                                                                                                     // packages and/or Homebrew.                                                                                                                                                                  //
  // Linux:        /usr/share/osquery/packs
  // OS X:         /var/osquery/packs                                                                                                                                                           // Homebrew:     /usr/local/share/osquery/packs
  // make install: {PREFIX}/share/osquery/packs
  //
  "packs": {
    "osquery-monitoring": "/usr/share/osquery/packs/osquery-monitoring.conf",
    "incident-response": "/usr/share/osquery/packs/incident-response.conf",
    "it-compliance": "/usr/share/osquery/packs/it-compliance.conf",
    // "osx-attacks": "/usr/share/osquery/packs/osx-attacks.conf",
    "vuln-management": "/usr/share/osquery/packs/vuln-management.conf",
    "hardware-monitoring": "/usr/share/osquery/packs/hardware-monitoring.conf"
  }
}
```
l.114 is out of bounds. I checked packs also but didn't see any unusual characters.

As more testing goes, it seems vuln-management pack is the cause with the query unauthenticated_sparkle_feeds.
If I removed it, works fine on linux
On Mac, osx-attacks also have same error line 8 column 31 which is description for WireLurker... and for all descriptions with an url, it does the same which means most of the file. Once remove, it's fine

when tested interactively on mac, I get no errors. but no output either.
```
# osqueryi
Using a virtual database. Need help, type '.help'
osquery> select feeds.*, p2.value as sparkle_version from (select a.name as app_name, a.path as app_path, a.bundle_identifier as bundle_id, p.value as feed_url from (select name, path, bundle_identifier from apps) a, preferences p where p.path = a.path || '/Contents/Info.plist' and p.key = 'SUFeedURL' and feed_url like 'http://%') feeds left outer join preferences p2 on p2.path = app_path || '/Contents/Frameworks/Sparkle.framework/Resources/Info.plist' where (p2.key = 'CFBundleShortVersionString' OR coalesce(p2.key, '') = '');
osquery>
```

**Comment by fuzzball5000** [comment] 2017-01-03 13:48
osqueryi doesn't ingest the config; it's an interactive shell for running queries, therefore I would expect that to work, barring any other problems.

Copying your config verbatiam into http://jsonlint.com/ is showing that it isn't valid data, could something have got changed in the copy/paste process?

**Comment by juju4** [comment] 2017-01-03 14:03
I got "Expecting 'STRING', '}', got 'undefined'" on both files, my osquery.json and ./tools/deployment/osquery.example.conf.
got also error if I copy/paste https://raw.githubusercontent.com/facebook/osquery/master/packs/osx-attacks.conf

but for now, both seems to be processed fine by osqueryd and profile.py when removing previously discussed entries

**Comment by PoppySeedPlehzr** [comment] 2017-01-03 20:12
Have you tried using the `--config_check` flag? I'm copy-pasting the osx-attacks.conf file and it's looking fine for me:
```
Downloads ❯ osqueryi --config_check --config_path=./osx_pack.json
Downloads ❯
```
If the JSON doesn't parse correctly you'll get this:
```
Downloads ❯ osqueryi --config_check --config_path=./osx_pack.json
Error reading config: Error parsing the config JSON
```
I'd say @fuzzball5000 likely has the answer, and that there's a json issue somewhere.

**Comment by fuzzball5000** [comment] 2017-01-03 20:47
Actually, http://jsonlint.com/ might be a red herring. The example conf is apparently not RFC 4627 compliant, due to the // characters. 

--config_check is validating your pasted example fine... Indulge my curiosity please, and do $ file -bi /etc/osquery/osquery.conf and paste the results here.

**Comment by theopolis** [comment] 2017-01-04 04:47
Ah, right, osquery does some "fixes" to input JSON to make it work. We support escaped newlines and `//` c++ style comments. This is because the older 1.58 boost JSON property tree libraries did the same fixes and we wanted to remain backward compatible.

**Comment by theopolis** [comment] 2017-01-04 04:47
To make `profile.py` work we'll need to apply the same support for comments.

**Comment by juju4** [comment] 2017-01-04 10:47
No issue. working with above changes

```
# file -bi /etc/osquery/osquery.conf 
text/plain; charset=us-ascii
root@dpjenkins:/tmp/osquery# osqueryi --config_check --config_path=/etc/osquery/osquery.conf
# osqueryi --config_check --config_path=/usr/share/osquery/packs/vuln-management.conf
# osqueryi --config_check --config_path=/usr/share/osquery/packs/vuln-management.conf.orig 
# osqueryi --config_check --config_path=/usr/share/osquery/packs/osx-attacks.conf
#
```

**Comment by jedi22** [comment] 2017-05-26 05:41
`./tools/analysis/profile.py --config /etc/osquery/osquery.conf --shell /usr/bin/osqueryi --count 1 --rounds 4 --verbose `

Worked for me when I ran on master now, going to close this task but reopen it if you have more issues or I missed something!

**Comment by juju4** [comment] 2017-05-26 10:19
not on this side
```
$ ./tools/analysis/profile.py --config /etc/osquery/osquery.conf --shell /usr/bin/osqueryi --count 1 --rounds 4 --verbose
Traceback (most recent call last):
  File "./tools/analysis/profile.py", line 342, in <module>
    queries = utils.queries_from_config(args.config)
  File "/opt/tmp/security-test/osquery/tools/analysis/../tests/utils.py", line 101, in queries_from_config
    packqueries = json.loads(packcontent)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 129 column 336 (char 6128)
$ cat /etc/osquery/osquery.conf
// Ansible managed
{
  // Configure the daemon below:
  "options": {
    // Select the osquery config plugin.
    "config_plugin": "filesystem",

    // Select the osquery logging plugin.
    "logger_plugin": "filesystem",

    // The log directory stores info, warning, and errors.
    // If the daemon uses the 'filesystem' logging retriever then the log_dir
    // will also contain the query results.
    //"logger_path": "/var/log/osquery",

    // Set 'disable_logging' to true to prevent writing any info, warning, error
    // logs. If a logging plugin is selected it will still write query results.
    //"disable_logging": "false",

    // Query differential results are logged as change-events to assist log
    // aggregation operations like searching and transactons.
    // Set 'log_results_events' to log differentials as transactions.
    //"log_result_events": "true",

    // Splay the scheduled interval for queries.
    // This is very helpful to prevent system performance impact when scheduling
    // large numbers of queries that run a smaller or similar intervals.
    //"schedule_splay_percent": "10",

    // Write the pid of the osqueryd process to a pidfile/mutex.
    //"pidfile": "/var/osquery/osquery.pidfile",

    // Clear events from the osquery backing store after a number of seconds.
    "events_expiry": "3600",

    // A filesystem path for disk-based backing storage used for events and
    // query results differentials. See also 'use_in_memory_database'.
    //"database_path": "/var/osquery/osquery.db",

    // Comma-delimited list of table names to be disabled.
    // This allows osquery to be launched without certain tables.
    //"disable_tables": "foo_bar,time",

    // Enable debug or verbose debug output when logging.
    "verbose": "false",

    // The number of threads for concurrent query schedule execution.
    "worker_threads": "2",

    // Enable schedule profiling, this will fill in averages and totals for
    // system/user CPU time and memory for every query in the schedule.
    // Add a query: "select * from osquery_schedule" to record the performances.
    "enable_monitor": "true"
  },

  // Define a schedule of queries:
  "schedule": {
    // This is a simple example query that outputs basic system information.
    "system_info": {
      // The exact query to run.
      "query": "SELECT hostname, cpu_brand, physical_memory FROM system_info;",
      // The interval in seconds to run this query, not an exact interval.
      "interval": 3600
    },
    "fim" : {
//      "query": "select target_path, category, time, action from file_events;",
      "query": "select * from file_events;",
      "removed": false,
      "interval": 900
    }
  },

  "file_paths": {
    "homes_sshdir": [
      "/root/.ssh/%%",
      "/home/%/.ssh/%%"
    ],
    "etc": [
      "/etc/%%"
    ],
    "tmp": [
      "/tmp/%%"
    ],
    "bin": [
      "/bin/%%",
      "/sbin/%%",
      "/usr/bin/%%",
      "/usr/sbin/%%",
      "/usr/local/bin/%%",
      "/usr/local/sbin/%%",
      "/opt/bin/%%",
      "/opt/sbin/%%"
    ],
    "webroot": [
      "/var/www/%%"
    ]
  },

  // Decorators are normal queries that append data to every query.
  "decorators": {
    "load": [
      "SELECT uuid AS host_uuid FROM system_info;",
      "SELECT user AS username FROM logged_in_users ORDER BY time DESC LIMIT 1;"
    ]
  },

  // Add default osquery packs or install your own.
  //
  // There are several 'default' packs installed with 'make install' or via
  // packages and/or Homebrew.
  //
  // Linux:        /usr/share/osquery/packs
  // OS X:         /var/osquery/packs
  // Homebrew:     /usr/local/share/osquery/packs
  // make install: {PREFIX}/share/osquery/packs
  //
  "packs": {
    "osquery-monitoring": "/usr/share/osquery/packs/osquery-monitoring.conf",
    "incident-response": "/usr/share/osquery/packs/incident-response.conf",
    "it-compliance": "/usr/share/osquery/packs/it-compliance.conf",
    "vuln-management": "/usr/share/osquery/packs/vuln-management.conf",
    "hardware-monitoring": "/usr/share/osquery/packs/hardware-monitoring.conf",
    "osquery-custom-pack": "/usr/share/osquery/packs/osquery-custom-pack.conf"
  }
}
$ osqueryi --config_path /etc/osquery/osquery.conf --config_check --verbose
I0526 06:01:31.449367 32390 init.cpp:383] osquery initialized [version=2.4.2]
I0526 06:01:31.449436 32390 extensions.cpp:295] Could not autoload extensions: Failed reading: /etc/osquery/extensions.load
I0526 06:01:31.449456 32390 extensions.cpp:308] Could not autoload modules: Failed reading: /etc/osquery/modules.load
$ egrep -v '^\s*//' /etc/osquery/osquery.conf | tee /tmp/a | python -mjson.tool
[dump config without error]
```

Don't see any changes on 
https://github.com/facebook/osquery/blob/master/tools/analysis/profile.py

upstream sample config
```
$ osqueryi --config_path tools/deployment/osquery.example.conf --config_check --verbose
I0526 06:08:24.962916  1325 init.cpp:383] osquery initialized [version=2.4.2]
I0526 06:08:24.962980  1325 extensions.cpp:295] Could not autoload extensions: Failed reading: /etc/osquery/extensions.load
I0526 06:08:24.962999  1325 extensions.cpp:308] Could not autoload modules: Failed reading: /etc/osquery/modules.load
$ egrep -v '^\s*//' tools/deployment/osquery.example.conf | tee /tmp/a | python -mjson.tool
[OK]
$ ./tools/analysis/profile.py --config tools/deployment/osquery.example.conf --shell /usr/bin/osqueryi --count 1 --rounds 4 --verboseProfiling query: SELECT hostname, cpu_brand, physical_memory FROM system_info;
 D:0  C:0  M:1  F:0  U:0  system_info (1/4): duration: -0.492256879807 cpu_time: 0.0 memory: 9338880 fds: 3 utilization: 0 
 D:0  C:0  M:1  F:0  U:0  system_info (2/4): duration: -0.489467144012 cpu_time: 0.0 memory: 9338880 fds: 3 utilization: 0 
 D:0  C:0  M:1  F:0  U:0  system_info (3/4): duration: -0.489886045456 cpu_time: 0.01 memory: 9334784 fds: 3 utilization: 2.0 
 D:0  C:0  M:1  F:0  U:0  system_info (4/4): duration: -0.493514060974 cpu_time: 0.0 memory: 9338880 fds: 3 utilization: 0 
 D:0  C:0  M:1  F:0  U:0  system_info   avg: duration: -0.491281032562 cpu_time: 0.0025 memory: 9337856.0 fds: 3.0 utilization: 0.5
```

If I go into the details, it's the vuln-management pack which causes issue
```
$ ./tools/analysis/profile.py --config osquery.conf --shell /usr/bin/osqueryi --count 1 --rounds 4 --verbose
Traceback (most recent call last):
  File "./tools/analysis/profile.py", line 342, in <module>
    queries = utils.queries_from_config(args.config)
  File "/opt/tmp/security-test/osquery/tools/analysis/../tests/utils.py", line 101, in queries_from_config
    packqueries = json.loads(packcontent)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 129 column 336 (char 6128)
```
so the `http://%` in unauthenticated_sparkle_feeds
https://github.com/facebook/osquery/blob/master/packs/vuln-management.conf#L129

I suppose c++ comments are fine now, not sure from which commit.

**Comment by juju4** [comment] 2017-05-26 10:35
also, minor issue, profile.py does not take into account platform values (running darwin queries on linux for example)

**Comment by jedi22** [comment] 2017-05-26 14:59
@juju4 My bad, I'll look into this more today

**Comment by jedi22** [comment] 2017-05-26 17:12
You were entirely correct, my testing last night was flawed as I accidentally did not include the packs correctly. My proposed solution to the problem is to replace the regex in utils:L80 with `\/\*[\*A-Za-z0-9\n\s\.\{\}\'\/\\\:]+\*\/|\(.*\)|\/\/.*|\x5c\x5c\x0a` and in all our conf files, place URLs within parentheses

**Comment by jedi22** [comment] 2017-05-26 21:09
`\/\*[\*A-Za-z0-9\n\s\.\{\}\'\/\\\:]+\*\/|\s+\/\/.*|^\/\/.*|\x5c\x5c\x0a` is the regex I'm currently playing with. It seems to solve most issues while only giving up JSON and a C style comment on the same line.

**Closed** 2017-05-29 22:02 UTC
Labels: bug, build/test, debt, up for grabs
