### ISSUE TITLE
windows osqueryi execute query not output data for extension table when execute with parameter --extension and --A

### ISSUE THREAD

**Issue by turtlejamesw** [facebook/osquery#4612] opened 2018-06-20 07:10 UTC
Details are as follows -

**(1) I git clone osquery source from github, and switch to 3.2.6 branch, and build all of source are successful**

**(2) i try to test example extension as following, i can query example table in osqueryi console**

C:\osquery\build\windows10\osquery\Release>
C:\osquery\build\windows10\osquery\Release>osqueryi.exe --allow_unsafe --extension example_extension.ext.exe
Using a [1mvirtual database[0m. Need help, type '.help'
osquery> Select * from example;
+--------------+-----------------+
| example_text | example_integer |
+--------------+-----------------+
| example      | 1               |
+--------------+-----------------+
osquery> .exit

**(3) i try to dump example extension table directly without console as following, but not data output, only error**

C:\osquery\build\windows10\osquery\Release>osqueryi.exe --allow_unsafe --extension example_extension.ext.exe --A example

Error querying table: example
E0620 02:07:12.024760  7736 example_extension.cpp:109] Extension socket not available: \\.\pipe\shell.em

**(4) i try to dump example extension table directly without console as following, but nothing output (--verbose)**
C:\osquery\build\windows10\osquery\Release>
C:\osquery\build\windows10\osquery\Release>osqueryi.exe --allow_unsafe --extension example_extension.ext.exe --A example --verbose
I0619 23:44:43.005470  7084 init.cpp:396] osquery initialized [version=3.2.6]
I0619 23:44:43.005970  7084 extensions.cpp:342] Could not autoload extensions: Failed reading: \ProgramData\osquery\extensions.load
I0619 23:44:43.008971  6796 interface.cpp:263] Extension manager service starting: \\.\pipe\shell.em
I0619 23:44:43.008971  7084 auto_constructed_tables.cpp:85] Removing stale ATC entries
I0619 23:44:43.008971  7084 init.cpp:669] Error reading config: config file does not exist: \ProgramData\osquery\osquery.conf
Error querying table: example
I0619 23:44:43.027593  3460 watcher.cpp:596] Created and monitoring extension child (1288): example_extension.ext.exe

C:\osquery\build\windows10\osquery\Release>I0619 23:44:43.040103  3748 init.cpp:399] osquery extension initialized [sdk=3.2.6]
E0619 23:44:46.071854  3748 example_extension.cpp:102] Extension socket not available: \\.\pipe\shell.em

**(5)Default builb-in tables are OK, but extension table can't**

**Does anyone meet this issue, and have any good idea to solved that???
i just want dump example extension table data to a file by windows CMD, not osqueryi console**

### What version of `osquery` are you using? What operating system. Be specific.
You can run this query to get the necessary details: 
```
osqueryd -S --line 'SELECT oi.version as osquery_version, os.version AS os_version, os.build AS os_build, os.platform AS os_platform FROM os_version AS os JOIN osquery_info as oi;'
```

### What did you see instead?
#

**Comment by turtlejamesw** [comment] 2018-06-20 07:15
C:\osquery\build\windows10\osquery\Release>osqueryi
Using a [1mvirtual database[0m. Need help, type '.help'
osquery>
osquery>
osquery> SELECT oi.version as osquery_version, os.version AS os_version, os.build AS os_build, os.platform AS os_platform FROM os_version AS os JOIN osquery_info as oi;
+-----------------+------------+----------+-------------+
| osquery_version | os_version | os_build | os_platform |
+-----------------+------------+----------+-------------+
| 3.2.6           | 10.0.14393 | 14393    | windows     |
+-----------------+------------+----------+-------------+
osquery>

**Comment by turtlejamesw** [comment] 2018-06-20 07:19
Details are as follows -

(1) I git clone osquery source from github, and switch to 3.2.6 branch, and build all of source are successful

(2) i try to test example extension as following, i can query example table in osqueryi console

C:\osquery\build\windows10\osquery\Release>
C:\osquery\build\windows10\osquery\Release>osqueryi.exe --allow_unsafe --extension example_extension.ext.exe
Using a [1mvirtual database[0m. Need help, type '.help'
osquery> Select * from example;
+--------------+-----------------+
| example_text | example_integer |
+--------------+-----------------+
| example      | 1               |
+--------------+-----------------+
osquery> .exit

(3) i try to dump example extension table directly without console as following, but nothing output

C:\osquery\build\windows10\osquery\Release>osqueryi.exe --allow_unsafe --extension example_extension.ext.exe --A example

(4) i try to dump example extension table directly without console as following, but nothing output (--verbose)
C:\osquery\build\windows10\osquery\Release>
C:\osquery\build\windows10\osquery\Release>osqueryi.exe --allow_unsafe --extension example_extension.ext.exe --A example --verbose
I0619 23:44:43.005470  7084 init.cpp:396] osquery initialized [version=3.2.6]
I0619 23:44:43.005970  7084 extensions.cpp:342] Could not autoload extensions: Failed reading: \ProgramData\osquery\extensions.load
I0619 23:44:43.008971  6796 interface.cpp:263] Extension manager service starting: \\.\pipe\shell.em
I0619 23:44:43.008971  7084 auto_constructed_tables.cpp:85] Removing stale ATC entries
I0619 23:44:43.008971  7084 init.cpp:669] Error reading config: config file does not exist: \ProgramData\osquery\osquery.conf
Error querying table: example
I0619 23:44:43.027593  3460 watcher.cpp:596] Created and monitoring extension child (1288): example_extension.ext.exe

C:\osquery\build\windows10\osquery\Release>I0619 23:44:43.040103  3748 init.cpp:399] osquery extension initialized [sdk=3.2.6]
E0619 23:44:46.071854  3748 example_extension.cpp:102] Extension socket not available: \\.\pipe\shell.em


(5)Default builb-in tables are OK, but extension table can't

**Comment by muffins** [comment] 2018-06-20 23:40
Hey there! Yeah this is _sort_ of expected behavior in my opinion, it could be that we'd benefit from re-organizing the process of some operations, but I'm not 100% that we actually _support_ this operation from the shell. If you checkout your output:
```
...
Error querying table: example
I0619 23:44:43.027593 3460 watcher.cpp:596] Created and monitoring extension child (1288): example_extension.ext.exe
...
```
The query executes _before_ the process has had a chance to load. I believe this is because we run these "one-off" queries quickly if we can, it's more intended to ask a fast question, whereas asking everything of your extensions is more designed to be queryed when you're running in the context of the daemon. I'll give others a chance to chime in and disagree with me :) But from my perspective this is sort of an expected behavior of the shell.

**Comment by muffins** [comment] 2018-06-22 04:37
@obelisk I think that while this particular case related only to Windows, this is the same behavior on Posix as well?
@turtlejamesw sounds good. Going to close this issue out for now, feel free to open if you'd like, or hit up [our slack](https://osquery-slack.herokuapp.com/) if you'd like to continue the conversation

**Closed by muffins** 2018-06-22 04:37 UTC
Labels: question

**Comment by turtlejamesw** [comment] 2018-06-25 02:04
Finally, I chose to migrate the code to the osquery core. This is feasible. Thanks all
