### ISSUE TITLE
can't build osquery on OS X

### ISSUE THREAD

**Issue by ErikGoldman** [facebook/osquery#4283] opened 2018-04-14 01:35 UTC
### What version of `osquery` are you using? What operating system. Be specific.
```
+-----------------+------------+----------+-------------+
| osquery_version | os_version | os_build | os_platform |
+-----------------+------------+----------+-------------+
| 2.6.1           | 10.13.3    | 17D47    | darwin      |
+-----------------+------------+----------+-------------+'
```

building on 67dd49a680dcad702ceb3e9c4cdef33fba07cf7a (and other versions) produces this error on my machine:

```
[58%] Building CXX object osquery/events/CMakeFiles/osquery_events_darwin.dir/darwin/kernel_util.cpp.o
[...]/osquery/osquery/events/darwin/kernel_util.cpp:52:12: error: qualified reference to 'SQL' is a constructor name rather than a type in this context
      SQL::SQL(
           ^
1 error generated.
```

my commands to build were:
```
git clone https://github.com/facebook/osquery
cd osquery
make deps && make
```

any idea what's going on? I can post a longer log file for the build but nothing else seemed particularly relevant.

thanks!

**Comment by obelisk** [comment] 2018-04-16 14:43
Have you pulled recently? 2.6.1 is quite old and many things have changed since then so it's quite possible that just pulling the new code will fix the issue.

**Comment by ilovezfs** [comment] 2018-04-16 15:20
@obelisk we're seeing this in Homebrew CI now too with 3.2.2 https://jenkins.brew.sh/job/Homebrew%20Testing/625/version=high_sierra/testReport/junit/brew-test-bot/high_sierra/install_osquery/

Maybe caused by Xcode 9.3?

**Comment by obelisk** [comment] 2018-04-16 15:50
Investigating.

**Comment by obelisk** [comment] 2018-04-16 18:11
Fix is here: #4291

**Comment by obelisk** [comment] 2018-04-16 19:25
Fix is landed and build should work now!

**Comment by muffins** [comment] 2018-04-17 03:12
Closing this out, feel free to reopen if you have more issues :)

**Closed by muffins** 2018-04-17 03:12 UTC
Labels: bug, build/test, cause identified, macOS
