### ISSUE TITLE
osquery crashes with "JSON object was not an array" on a specific host for a specific query

### ISSUE THREAD

**Issue by danielpops** [facebook/osquery#4741] opened 2018-07-20 23:54 UTC
### What version of `osquery` are you using? What operating system. Be specific.
```
osquery_version = 3.2.6
     os_version = 14.04, Trusty Tahr
       os_build =
    os_platform = ubuntu
```
### What's happening?

osquery is crashing (interestingly, only on one particular host) with `JSON object was not an array`

```
$ sudo osqueryd --flagfile=/etc/osquery/osquery.flags --config_path=/etc/osquery/osquery.conf --verbose
I0720 16:37:23.187543 18563 init.cpp:396] osquery initialized [version=3.2.6]
I0720 16:37:23.215203 18563 system.cpp:368] Found stale process for osqueryd (18390)
I0720 16:37:23.215361 18563 system.cpp:400] Writing osqueryd pid (18563) to /var/run/osqueryd.pidfile
I0720 16:37:23.215569 18563 extensions.cpp:342] Could not autoload extensions: Failed reading: /etc/osquery/extensions.load
I0720 16:37:23.216801 18564 watcher.cpp:554] osqueryd watcher (18563) executing worker (18565)
I0720 16:37:23.227064 18565 init.cpp:393] osquery worker initialized [watcher=18563]
I0720 16:37:23.227751 18565 rocksdb.cpp:132] Opening RocksDB handle: /var/osquery/osquery.db
I0720 16:37:24.588136 18565 auto_constructed_tables.cpp:85] Removing stale ATC entries
I0720 16:37:24.588208 18585 interface.cpp:263] Extension manager service starting: /var/osquery/osquery.em
I0720 16:37:33.708626 18565 aws_util.cpp:423] Using AWS region from flag: us-west-1
I0720 16:37:33.711607 18565 aws_kinesis.cpp:81] Kinesis logging initialized with stream: osquery_yelp
I0720 16:37:33.732216 18565 events.cpp:825] Event publisher not enabled: auditeventpublisher: Publisher disabled via configuration
I0720 16:37:33.732304 18565 events.cpp:825] Event publisher not enabled: syslog: Publisher disabled via configuration
I0720 16:37:33.732947 18565 events.cpp:1079] Error registering subscriber: process_file_events: Subscriber disabled via configuration
I0720 16:37:33.733067 18565 events.cpp:1079] Error registering subscriber: socket_events: Subscriber disabled via configuration
I0720 16:37:33.775835 18565 main.cpp:109] Not starting the distributed query service: Distributed query service not enabled.
I0720 16:37:33.776688 18803 events.cpp:746] Starting event publisher run loop: udev
I0720 16:37:33.776787 18802 events.cpp:746] Starting event publisher run loop: inotify
I0720 16:37:41.795181 18800 aws_log_forwarder.h:222] aws_kinesis: Successfully sent 1 out of 1 log records
I0720 16:37:58.850232 18800 aws_log_forwarder.h:222] aws_kinesis: Successfully sent 14 out of 14 log records
I0720 16:38:15.704350 18800 aws_log_forwarder.h:222] aws_kinesis: Successfully sent 1 out of 1 log records
I0720 16:38:32.401484 18800 aws_log_forwarder.h:222] aws_kinesis: Successfully sent 1 out of 1 log records
I0720 16:38:49.145846 18800 aws_log_forwarder.h:222] aws_kinesis: Successfully sent 1 out of 1 log records
I0720 16:38:56.832443 18804 scheduler.cpp:83] Executing scheduled query docker_processes: SELECT value, name, parent, pgroup, pid FROM docker_container_processes AS dcp JOIN docker_container_labels AS dcl WHERE dcp.id=dcl.id;
E0720 16:38:56.842144 18804 scheduler.cpp:130] Error adding new results to database: JSON object was not an array
```

### What have you already tried?
Sure enough, on this one particular host, there is no 
danielpops@host:~ [16:50:01] ✓
$ echo "SELECT value, name, parent, pgroup, pid FROM docker_container_processes AS dcp JOIN docker_container_labels AS dcl WHERE dcp.id=dcl.id;" | osqueryi
danielpops@host:~ [16:50:13] ✓
$ echo $?
0

There is one docker container running on the host, so it's weird that the query has no results, and it's also weird that this causes osquery to crash.

### What did you expect to see?
results from the query

### What did you see instead?
an error and a crash

**Comment by muffins** [comment] 2018-07-23 16:49
@danielpops could you be able to send me the `osquery.db` that's getting hooked up from `osqueryi`? My bet is that there's something residual in the default DB that osqueryi is grabbing. This might not necessarily be the cause of the crash, but we've had issues with the Database upgrade migrations from < 3.0 to 3.2+

**Comment by muffins** [comment] 2018-07-25 00:08
@danielpops any chance you saw the message I left? Would it be possible to get your configuration and maybe the database that you are seeing this crash with?

**Comment by danielpops** [comment] 2018-07-26 01:09
Took this offline with @muffins over slack. something about the db migration from v0 to v1 didn't go quite right. It's still not entirely clear _why_ after poking around in the DB. The advice is to nuke and move forward, especially given that this is only happening on a single host out of several hundred. I might try to toy around with rocksdb tool `ldb` to see if i can recover without nuking history, but it probably won't be worth the effort.

**Comment by fmanco** [comment] 2018-08-20 08:53
@danielpops I'll close this then. Feel free to re-open if you still have issues.

**Closed by fmanco** 2018-08-20 08:53 UTC
Labels: bug, database

**Comment by danielpops** [comment] 2018-09-10 21:08
I finally got around to upgrading our fleet across the board and many many hosts exhibited this problem. /me re-opens
