### ISSUE TITLE
osqueryd process hangs

### ISSUE THREAD

**Issue by nlsun** [facebook/osquery#1277] opened 2015-06-30 17:40 UTC
Here are all the details that I could think of. It just seems like the process hangs without output. I considered that this might be an issue where it's just running into memory limits again but in those cases the process would actually crash.

```
$ cat /etc/redhat-release
CentOS Linux release 7.0.1406 (Core)



$ osqueryd --version
osqueryd version 1.4.6


$ ps aux | grep -i '[o]squery'
root     16848  0.0  0.0 296436  3164 ?        SNsl Jun26   2:32 osqueryd --config_path=/etc/osquery/osquery.conf --pidfile=/var/run/osqueryd.pid --daemonize=true



$ tail /var/log/osquery/osqueryd.results.log
{"name":"outbound_connections","hostIdentifier":"nsun.vm.ny5.etsy.com","calendarTime":"Fri Jun 26 17:50:38 2015 UTC","unixTime":"1435341038","columns":{"cmdline":"\/opt\/lumberjack\/bin\/lumberjack -config \/etc\/lumberjack.conf -spool-size 500 -idle-flush-time 5s -from-beginning=true -threads 9 -num-workers 9 -progress-file \/var\/run\/.lumberjack -pid-file \/var\/run\/lumberjack.pid -log-file \/var\/log\/lumberjack.log -temp-dir \/var\/run","local_port":"54735","md5":"021a1e4e7539880136b67bdc0430968a","name":"lumberjack","path":"\/opt\/lumberjack\/bin\/lumberjack","pid":"25445","remote_address":"10.100.48.16","remote_port":"9991","username":"root"},"action":"removed"}
{"name":"outbound_connections","hostIdentifier":"nsun.vm.ny5.etsy.com","calendarTime":"Fri Jun 26 17:50:38 2015 UTC","unixTime":"1435341038","columns":{"cmdline":"php \/var\/etsy\/current\/bin\/gci\/process_payments.php","local_port":"40080","md5":"2e7838115a3454149fcc5e9055cabab8","name":"php","path":"\/usr\/bin\/php","pid":"15223","remote_address":"10.101.64.59","remote_port":"3323","username":"apache"},"action":"removed"}
{"name":"outbound_connections","hostIdentifier":"nsun.vm.ny5.etsy.com","calendarTime":"Fri Jun 26 17:50:38 2015 UTC","unixTime":"1435341038","columns":{"cmdline":"php \/var\/etsy\/current\/bin\/gci\/process_payments.php","local_port":"47525","md5":"2e7838115a3454149fcc5e9055cabab8","name":"php","path":"\/usr\/bin\/php","pid":"15223","remote_address":"10.100.14.13","remote_port":"3323","username":"apache"},"action":"removed"}
{"name":"outbound_connections","hostIdentifier":"nsun.vm.ny5.etsy.com","calendarTime":"Fri Jun 26 17:50:38 2015 UTC","unixTime":"1435341038","columns":{"cmdline":"znc","local_port":"52086","md5":"c1350d20cb68c4f9c478b4cf6cc0fbdb","name":"znc","path":"\/usr\/bin\/znc","pid":"23966","remote_address":"91.217.189.42","remote_port":"6667","username":"nsun"},"action":"removed"}
{"name":"network_interface_details","hostIdentifier":"nsun.vm.ny5.etsy.com","calendarTime":"Fri Jun 26 17:50:56 2015 UTC","unixTime":"1435341056","columns":{"ibytes":"699229044","ierrors":"0","interface":"lo","ipackets":"2842922","last_change":"-1","mac":"00:00:00:00:00:00","metric":"0","mtu":"65536","obytes":"699229044","oerrors":"0","opackets":"2842922","type":"772"},"action":"added"}
{"name":"network_interface_details","hostIdentifier":"nsun.vm.ny5.etsy.com","calendarTime":"Fri Jun 26 17:50:56 2015 UTC","unixTime":"1435341056","columns":{"ibytes":"2033564974","ierrors":"0","interface":"eth0","ipackets":"223113869","last_change":"-1","mac":"52:54:00:00:09:81","metric":"0","mtu":"1500","obytes":"1059195873","oerrors":"0","opackets":"86921452","type":"1"},"action":"added"}
{"name":"network_interface_details","hostIdentifier":"nsun.vm.ny5.etsy.com","calendarTime":"Fri Jun 26 17:51:29 2015 UTC","unixTime":"1435341089","columns":{"ibytes":"699238586","ierrors":"0","interface":"lo","ipackets":"2842962","last_change":"-1","mac":"00:00:00:00:00:00","metric":"0","mtu":"65536","obytes":"699238586","oerrors":"0","opackets":"2842962","type":"772"},"action":"added"}
{"name":"network_interface_details","hostIdentifier":"nsun.vm.ny5.etsy.com","calendarTime":"Fri Jun 26 17:51:29 2015 UTC","unixTime":"1435341089","columns":{"ibytes":"2033602004","ierrors":"0","interface":"eth0","ipackets":"223114152","last_change":"-1","mac":"52:54:00:00:09:81","metric":"0","mtu":"1500","obytes":"1059255666","oerrors":"0","opackets":"86921875","type":"1"},"action":"added"}
{"name":"most_mem_usage_10","hostIdentifier":"nsun.vm.ny5.etsy.com","calendarTime":"Fri Jun 26 17:51:46 2015 UTC","unixTime":"1435341106","columns":{"name":"builda","pid":"14883"},"action":"added"}
{"name":"most_mem_usage_10","hostIdentifier":"nsun.vm.ny5.etsy.com","calendarTime":"Fri Jun 26 17:51:46 2015 UTC","unixTime":"1435341106","columns":{"name":"chef-client","pid":"4016"},"action":"removed"}



$ tail /var/log/osquery/osqueryd.INFO
I0618 16:04:23.900419 18337 scheduler.cpp:83] Executing query: select * from interface_details
I0618 16:04:23.903161 18337 scheduler.cpp:131] Found results for query (network_interface_details) for host: nsun.vm.ny5.etsy.com
I0618 16:04:23.903870 18337 scheduler.cpp:83] Executing query: select rpf.package, rpf.path, rpf.size as psize, fi.size as fsize from rpm_package_files as rpf, file as fi where rpf.package='php' and rpf.path=fi.path and rpf.size<>fi.size and fi.is_dir=0 and is_link=0;
I0618 16:04:25.947188 18337 scheduler.cpp:83] Executing query: select * from arp_cache
I0618 16:04:53.954053 18337 scheduler.cpp:83] Executing query: select distinct user from logged_in_users where user is not '';
I0618 16:05:05.957617 18337 scheduler.cpp:83] Executing query: select pid, name from processes order by phys_footprint desc limit 10;
I0618 16:05:22.117877 18337 scheduler.cpp:83] Executing query: select name, size, used_by, address from kernel_modules where status='Live';
I0618 16:05:22.131593 18337 scheduler.cpp:83] Executing query: select * from interface_details
I0618 16:05:22.134529 18337 scheduler.cpp:131] Found results for query (network_interface_details) for host: nsun.vm.ny5.etsy.com
I0618 16:05:24.136379 18337 scheduler.cpp:83] Executing query: select usr.username, proc.uid, lp.pid, lp.port, lp.protocol, lp.family, lp.address from listening_ports as lp, processes as proc, users as usr where lp.pid<>'-1' and lp.pid=proc.pid and proc.uid=usr.uid;



$ tail /var/log/osquery/osqueryd.WARNING
Log file created at: 2015/06/17 19:28:12
Running on machine: nsun.vm.ny5.etsy.com
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
W0617 19:28:12.825378 25654 config.cpp:219] Error parsing config JSON: <unspecified file>(38): expected ',' or '}'



$ cat /etc/osquery/osquery.conf
{
  "options": {
    "host_identifier": "hostname",
    "schedule_splay_percent": 10
  },
  "schedule": {
    "distinct_users": {
      "query": "select distinct user from logged_in_users where user is not '';",
      "interval": 60
    },
    "most_mem_usage_10": {
      "query": "select pid, name from processes order by phys_footprint desc limit 10;",
      "interval": 60
    },
    "live_kernel_mod": {
      "query": "select name, size, used_by, address from kernel_modules where status='Live';",
      "interval": 120
    },
    "arp_cache": {
      "query": "select * from arp_cache",
      "interval": 120
    },
    "network_interface_details": {
      "query": "select * from interface_details",
      "interval": 30,
      "removed": false
    },
    "outbound_connections": {
      "query": "select user.username, proc.name, hash.md5, socket.pid, proc.path, proc.cmdline, socket.local_port, socket.remote_port, socket.remote_address from process_open_sockets as socket, processes as proc, users as user, hash as hash where socket.local_port not in (select port from listening_ports) and socket.local_port != 0 and socket.pid = proc.pid and user.uid = proc.uid and hash.path = proc.path;",
      "interval": 180
    }
  }
}



$ systemctl status osqueryd.service
osqueryd.service - LSB: run osqueryd daemon
   Loaded: loaded (/etc/rc.d/init.d/osqueryd)
   Active: active (running) since Fri 2015-06-26 12:58:10 UTC; 4 days ago
   CGroup: /system.slice/osqueryd.service
           ├─ 4781                                                                                                  
           ├─16848 osqueryd --config_path=/etc/osquery/osquery.conf --pidfile=/var/run/osqueryd.pid --daemonize=true
           └─16854                                                                                                  

Jun 26 12:58:10 nsun.vm.ny5.etsy.com osqueryd[16848]: osqueryd started [version=1.4.6]
Jun 26 12:58:10 nsun.vm.ny5.etsy.com systemd[1]: Started LSB: run osqueryd daemon.
```

**Comment by theopolis** [comment] 2015-06-30 18:22
Hi @Rasoran! Sorry if I'm missing something obvious, what's the error or expected result here?

**Comment by Rasoran** [comment] 2015-07-01 02:26
Ah, the process stops outputting to the results log yet is still running.

**Comment by theopolis** [comment] 2015-07-01 03:11
Is it possible to trigger the state where the daemon is running but no logs are emitted quickly?

Can you run with 1.4.7 and the following `/etc/osquery/osquery.conf`, which has verbose mode enabled? My first thought is something is consistently triggering a worker failure: (1) osqueryd determines the worker [pid 16854] has allocated too much memory or is spinning CPU for too long, (2) the worker is hitting an uncaught exception and aborting. In both cases there should be a warning log line emitted. I'm concerned that the `WARNING` log is so sparse given the pause of events. This "**lack of warning log**" condition may be the error/bug we're experiencing here.

```json
{
  "options": {
    "host_identifier": "hostname",
    "schedule_splay_percent": 10,
    "verbose": true
  },
  "schedule": {
    "distinct_users": {
      "query": "select distinct user from logged_in_users where user is not '';",
      "interval": 60
    },
    "most_mem_usage_10": {
      "query": "select pid, name from processes order by phys_footprint desc limit 10;",
      "interval": 60
    },
    "live_kernel_mod": {
      "query": "select name, size, used_by, address from kernel_modules where status='Live';",
      "interval": 120
    },
    "arp_cache": {
      "query": "select * from arp_cache",
      "interval": 120
    },
    "network_interface_details": {
      "query": "select * from interface_details",
      "interval": 30,
      "removed": false
    },
    "outbound_connections": {
      "query": "select user.username, proc.name, hash.md5, socket.pid, proc.path, proc.cmdline, socket.local_port, socket.remote_port, socket.remote_address from process_open_sockets as socket, processes as proc, users as user, hash as hash where socket.local_port not in (select port from listening_ports) and socket.local_port != 0 and socket.pid = proc.pid and user.uid = proc.uid and hash.path = proc.path;",
      "interval": 180
    }
  }
}
```

So I think I can reproduce this condition using the following config, verbose mode debug, then inspecting the logs. Here's an example of how to trigger the performance limits, check this example schedule that will hog a lot of CPU `~/osquery-testing/osquery.conf`:
```json
{
  "schedule": {
    "death": {
      "query": "select * from processes p JOIN hash on p.path = hash.path",
      "interval": 1
    }
  }
}  
```

Then I can do something like:
```
$ mkdir osquery-testing; cd osquery-testing;
# Drop contents from config above into ./osquery.conf

$ osqueryd --pidfile pid --database_path ./osquery.db --logger_path . --config_path ./osquery.conf --verbose
I0630 20:04:19.138855 27565 init.cpp:193] osquery initialized [version=1.4.7-24-g5ef01b4]
I0630 20:04:19.154794 27565 system.cpp:131] Found stale process for osqueryd (27528) removing pidfile
I0630 20:04:19.154897 27565 system.cpp:166] Writing osqueryd pid (27565) to pid
I0630 20:04:19.154992 27565 extensions.cpp:171] Could not autoload extensions: Failed reading: /etc/osquery/extensions.load
I0630 20:04:19.156505 27570 watcher.cpp:356] osqueryd watcher (27565) executing worker (27571)
I0630 20:04:19.164625 27571 init.cpp:190] osquery worker initialized [watcher=27571]
I0630 20:04:19.164902 27571 extensions.cpp:178] Could not autoload modules: Failed reading: /etc/osquery/modules.load
I0630 20:04:19.164995 27571 db_handle.cpp:115] Opening RocksDB handle: ./osquery.db
I0630 20:04:19.236167 27571 config.cpp:71] Updating config with source: ./osquery.conf
I0630 20:04:19.237009 27579 scheduler.cpp:83] Executing query: select * from processes p JOIN hash on p.path = hash.path
I0630 20:04:19.236913 27577 events.cpp:429] Starting event publisher run loop: inotify
I0630 20:04:19.237006 27578 events.cpp:429] Starting event publisher run loop: udev
W0630 20:04:25.157521 27570 watcher.cpp:292] osqueryd worker system performance limits exceeded
W0630 20:04:25.157570 27570 watcher.cpp:310] osqueryd worker respawning too quickly
I0630 20:04:32.158771 27570 watcher.cpp:356] osqueryd watcher (27565) executing worker (27594)
I0630 20:04:32.167721 27594 init.cpp:190] osquery worker initialized [watcher=27594]
I0630 20:04:32.168090 27594 extensions.cpp:178] Could not autoload modules: Failed reading: /etc/osquery/modules.load
I0630 20:04:32.168257 27594 db_handle.cpp:115] Opening RocksDB handle: ./osquery.db
I0630 20:04:32.256793 27594 config.cpp:71] Updating config with source: ./osquery.conf
I0630 20:04:32.257755 27602 scheduler.cpp:83] Executing query: select * from processes p JOIN hash on p.path = hash.path
I0630 20:04:32.257750 27601 events.cpp:429] Starting event publisher run loop: udev
I0630 20:04:32.257676 27600 events.cpp:429] Starting event publisher run loop: inotify
^C
```

Finally the `osqueryd.WARNING` symlink and logfile produced only contain:
```
Log file created at: 2015/06/30 20:04:32
Running on machine: maverics
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
```

**Comment by Rasoran** [comment] 2015-07-01 16:00
So I got another hanging process and here's the verbose log.

    $ tail osqueryd.INFO
    I0701 15:39:59.542768 14494 scheduler.cpp:83] Executing query: select * from interface_details
    I0701 15:40:22.551571 14494 scheduler.cpp:83] Executing query: select * from arp_cache
    I0701 15:40:22.553346 14494 arp_cache.cpp:38] Empty or failed arp table.
    I0701 15:40:26.554872 14494 scheduler.cpp:83] Executing query: select pid, name from processes order by phys_footprint desc limit 10;
    E0701 15:40:26.557006 14494 registry.cpp:300] table registry processes plugin caused exception: boost::filesystem::directory_iterator::construct: Too many open files: "/proc"
    I0701 15:40:32.558825 14494 scheduler.cpp:83] Executing query: select * from interface_details
    I0701 15:40:36.560683 14494 scheduler.cpp:83] Executing query: select distinct user from logged_in_users where user is not '';
    I0701 15:40:42.562981 14494 scheduler.cpp:83] Executing query: select name, size, used_by, address from kernel_modules where status='Live';
    I0701 15:40:42.564108 14494 kernel_modules.cpp:37] Cannot read kernel modules from: /proc/modules
    I0701 15:41:05.569460 14494 scheduler.cpp:83] Executing query: select * from interface_details

**Comment by theopolis** [comment] 2015-07-01 17:46
Ok! Thanks for the update @Rasoran, I'm working on a few changes today that will (A) emit more detailed/helpful logs and (B) relax some of the process-lifetime memory allocations. This should at least help us debug a bit more if you don't mind installing a debug build? I'm planning to have a proposed fix as a pull request by the EOD today!

**Comment by Rasoran** [comment] 2015-07-01 17:59
Yeah a debug build is fine.

**Comment by theopolis** [comment] 2015-07-08 07:34
Ok let's try: https://jenkins.osquery.io/userContent/build/centos7/osquery-1.4.7-61-gba28b47.rpm.

That will at least include better `WARNING` logs.

And then add `"registry_exceptions": true` to the options list. I don't have high confidence that will identify the problem, if there was a caught exception it will soon generate a crash report/log line.

**Comment by theopolis** [comment] 2015-07-09 05:49
After debugging and doing some code review of the networking parts of the linux tables, #1312, might be the source of the hangs. There are some outstanding bugs with `interface_addresses` that seems to share most of the implementation with `interface_details` (go figure). 

I'm not sure why your schedule would not progress past the `network_interface_details` query though. I will look into that ASAP but mimicking your schedule and inducing a crash in the worker at `interface_details`-- as well as review the scheduler's time accounting.

**Comment by theopolis** [comment] 2015-07-11 00:32
Here's the new unstable RPM that should include the fix! https://jenkins.osquery.io/userContent/build/centos7/osquery-1.4.7-67-g370290d.rpm

**Comment by Rasoran** [comment] 2015-07-13 13:37
I actually didn't manage to reproduce my crash with the previous debug build but I'll test out the new build as well.

**Comment by theopolis** [comment] 2015-07-13 17:17
Ok cool, I'll close the issue for now. If we encounter the hang/crash again we can open and attempt to root-cause some more.

**Comment by morrigan** [comment] 2016-11-13 22:02
I have the same issue: osquery daemon stops after few minutes. In my setup I am using remote settings with Doorman and I get the results of the first query schedule. Also, I am running Ubuntu 16.04 and my current version of osqueryd is 2.1.0-3-g8fc8134.

In my local log files I got nothing, but they are sent to Doorman:
```
severity	filename	line	message

1	virtual_table.cpp	484	The shell_history table returns data based on the current user by default, consider JOINing against the users table
1	virtual_table.cpp	484	The shell_history table returns data based on the current user by default, consider JOINing against the users table
1	inotify.cpp	152	Could not read inotify handle
2	udev.cpp	79	Could not read udev monitor
2	udev.cpp	79	Could not read udev monitor
1	inotify.cpp	152	Could not read inotify handle```

**Comment by theopolis** [comment] 2016-11-15 07:07
Hi @morrigan! I'm hoping the issues you're seeing are a bit different than these from last year.

Do you mind posting your configuration and describing in a bit more detail your experience? I'm looking for more details around what constitutes a "stop". Does the daemon stop reporting ALL queries in the schedule, does it stop writing to the local log files too?

Is there one query you know will always return data?

**Comment by morrigan** [comment] 2016-11-15 10:13
@theopolis yeah, I think they are slightly different. I notice that service status changes from `active (running)` to `active (exited)` and I don't see it anymore in the process list. I have lots of queries and I know some will always return data and also there is "Last Check-in Date" in Doorman. None of it updates after first run. All queries have interval of 500 seconds. It's not writing in any of the local log files but that might be because of sending logs to server?

Since I am running remote settings, `/etc/osquery/osquery.flags` contents are:
```
--pidfile=/tmp/osquery.pid
--host_identifier=uuid
--database_path=/tmp/osquery.db
--config_plugin=tls
--config_tls_endpoint=/config
--config_tls_refresh=10
--config_tls_max_attempts=3
--enroll_tls_endpoint=/enroll
--enroll_secret_path=/etc/osquery/secret.key
--disable_distributed=false
--distributed_plugin=tls
--distributed_interval=10
--distributed_tls_max_attempts=3
--distributed_tls_read_endpoint=/distributed/read
--distributed_tls_write_endpoint=/distributed/write
--logger_plugin=tls
--logger_tls_endpoint=/log
--logger_tls_period=5
--tls_hostname=xxx.herokuapp.com
--verbose
--tls_dump=true
```

Now I am testing the same configuration on Linux Mint 18 and seems like no issues with it (yet).

**Comment by theopolis** [comment] 2016-12-31 02:40
Ah, sorry I missed this again, the issue age is causing organization issues for me. :(

@morrigan, do you mind opening a new issue with the results of your research / scoping of the problem?

**Closed by theopolis** 2016-12-31 02:40 UTC
Labels: bug, Linux
