### ISSUE TITLE
FIM not working Event Publisher failed setup

### ISSUE THREAD

**Issue by ppartyka** [facebook/osquery#3379] opened 2017-06-02 20:30 UTC
Hello! I'm trying to test the FIM functionality on CentOS 7 and I can't seem to work, the log:

> I0602 19:59:57.078984  2265 events.cpp:827] Event publisher failed setup: audit: Publisher disabled via configuration
I0602 19:59:57.079516  2265 events.cpp:827] Event publisher failed setup: kernel: Cannot access /dev/osquery
I0602 19:59:57.079538  2265 events.cpp:827] Event publisher failed setup: syslog: Publisher disabled via configuration
W0602 19:59:57.103209  2265 inotify.cpp:290] Could not add inotify watch on: /root/.ssh/

The Config:

```
{
  "options": {
    // select the osquery config plugin (filesystem is default)
    "config_plugin": "filesystem",

    // select the osquery logging plugin (filesystem is default)
    "logger_plugin": "filesystem",

    // the PATH of log direcroty
    "logger_path": "/var/log/osquery",

    // PID file of the daemon
    "pidfile": "/var/osquery/osquery.pidfile",

    // the number of threads for concurrent query
    "worker_threads": "2",

    // enable schedule profiling
    // if adding a query "select * from osquery_schedule" in schedule section,
    // it's possible to record the performances
    "enable_monitor": "true"
  },

  "schedule": {
    // for example, get CPU Time per 300 seconds
    "cpu_time": {
      "query": "SELECT * FROM cpu_time;",
      "interval": 150
    },
    // for example, get settings of resolv.conf per an hour
    "dns_resolvers": {
      "query": "SELECT * FROM dns_resolvers;",
      "interval": 150
    }
  },
  "file_events": {
    "query": "select * from file_events;",
    "removed": false,
    "interval": 150
    },
  "file_paths": {
    "passwd": [
        "/etc/passwd"
    ]
  },

   "packs": {
     // possible to include other configration files
     //"fim": "/usr/share/osquery/packs/fim.conf"
   }
}
```
As I understand it, I just have to declare file_paths and file_events per the documentation? Using the config I also get this with osqueryi:

```
osqueryi --config_path=/etc/osquery/osquery.conf
Using a virtual database. Need help, type '.help'
osquery> select * from file_events;
W0602 20:30:06.449472  2403 virtual_table.cpp:513] Table file_events is event-based but events are disabled
W0602 20:30:06.449574  2403 virtual_table.cpp:520] Please see the table documentation: https://osquery.io/docs/#file_events
osquery>
```

**Comment by poppyseedplehzr** [comment] 2017-06-02 22:30
Ah!  You'll need to add a `--disable_events=false` flag in your invocation, so try:
```
osqueryi --config_path=/etc/osquery/osquery.conf --disable_events=false
```
But you'll also want to add that flag to the `osquery.conf` file.  I'd also encourage you to checkout our [Slack](https://osquery-slack.herokuapp.com/) group, which might get you faster responses to questions :)

**Comment by poppyseedplehzr** [comment] 2017-06-03 02:39
@ppartyka did that work for you? Would you mind if we close this issue out and move the conversation to [Slack](https://osquery-slack.herokuapp.com/)?

**Comment by ppartyka** [comment] 2017-06-03 19:29
@poppyseedplehzr Lets move it to slack, it didn't solve the issue still getting:

>>>I0603 19:20:01.979423 24361 events.cpp:827] Event publisher failed setup: audit: Publisher disabled via configuration
I0603 19:20:01.979904 24361 events.cpp:827] Event publisher failed setup: kernel: Cannot access /dev/osquery
I0603 19:20:01.979920 24361 events.cpp:827] Event publisher failed setup: syslog: Publisher disabled via configuration

After updating the config.

**Comment by theopolis** [comment] 2017-06-03 20:11
Use this config:
```json
{
  "options": {
    "config_plugin": "filesystem",
    "logger_plugin": "filesystem",
    "logger_path": "/var/log/osquery",
    "pidfile": "/var/osquery/osquery.pidfile",
  },

  "schedule": {
    "cpu_time": {
      "query": "SELECT * FROM cpu_time;",
      "interval": 150
    },
    "dns_resolvers": {
      "query": "SELECT * FROM dns_resolvers;",
      "interval": 150
    },
    "file_events": {
      "query": "select * from file_events;",
      "interval": 150
    }
  },
  "file_paths": {
    "passwd": [
        "/etc/passwd"
    ]
  }
}
```

**Comment by theopolis** [comment] 2017-06-03 21:16
@ppartyka I updated the config and removed the erroring `,`.

**Comment by poppyseedplehzr** [comment] 2017-06-07 01:25
Going to close this issue out as I believe we're actively diagnosing in Slack. Feel free to re-open if you encounter further issues! :)

**Closed by poppyseedplehzr** 2017-06-07 01:25 UTC
Labels: FIM, question

**Comment by lefthand** [comment] 2017-07-24 19:23
Did this problem ever get nailed down? I'm hitting the same issue and would love to get some ideas on what might be going on.

**Comment by gio-salvador** [comment] 2017-09-06 16:00
I'm facing the same issues. Any help appreciated.

Thanks!

**Comment by theopolis** [comment] 2017-09-08 04:48
The issue here was a bad config IIRC. @gio-salvador it looks like your inotify watches are added correctly. After modifying one of those files you do not see events in `file_events`?

**Comment by theopolis** [comment] 2017-09-08 05:09
Can you try to reproduce using this toy example:
```
» cat ./build/osquery.example.conf
{
  "options": {
    "config_plugin": "filesystem",
    "logger_plugin": "filesystem",
    "logger_path": "/var/log/osquery",
    "pidfile": "/var/osquery/osquery.pidfile"
  },

  "schedule": {
    "file_events": {
      "query": "select * from file_events;",
      "interval": 30
    }
  },
  "file_paths": {
    "passwd": [
        "/etc/passwd"
    ]
  }
}

------------------------------------------------------------
» sudo osqueryd --verbose --config_path ./build/osquery.example.conf
I0907 22:05:03.682195  7625 init.cpp:392] osquery initialized [version=2.7.0]
I0907 22:05:03.682260  7625 system.cpp:357] Writing osqueryd pid (7625) to /var/run/osqueryd.pidfile
I0907 22:05:03.682317  7625 extensions.cpp:288] Could not autoload extensions: Failed reading: /etc/osquery/extensions.load
I0907 22:05:03.682835  7626 watcher.cpp:513] osqueryd watcher (7625) executing worker (7627)
I0907 22:05:03.686282  7627 init.cpp:389] osquery worker initialized [watcher=7625]
I0907 22:05:03.686353  7627 rocksdb.cpp:214] Opening RocksDB handle: /var/osquery/osquery.db
I0907 22:05:03.779986  7634 interface.cpp:327] Extension manager service starting: /var/osquery/osquery.em
I0907 22:05:03.820140  7627 events.cpp:824] Event publisher failed setup: audit: Publisher disabled via configuration
I0907 22:05:03.820235  7627 events.cpp:824] Event publisher failed setup: kernel: Cannot access /dev/osquery
I0907 22:05:03.820246  7627 events.cpp:824] Event publisher failed setup: syslog: Publisher disabled via configuration
I0907 22:05:03.905434  7627 events.cpp:1077] Error registering subscriber: socket_events: Subscriber disabled via configuration
I0907 22:05:03.929072  7627 file_events.cpp:68] Added file event listener to: /etc/passwd
I0907 22:05:03.929158  7627 daemon.cpp:37] Not starting the distributed query service: Distributed query service not enabled.
I0907 22:05:03.929172  7635 events.cpp:745] Starting event publisher run loop: inotify
I0907 22:05:03.929217  7636 events.cpp:745] Starting event publisher run loop: udev
I0907 22:05:04.929529  7637 scheduler.cpp:75] Executing scheduled query file_events: select * from file_events;
^Z
[1]  + 7621 suspended  sudo osqueryd --verbose --config_path ./build/osquery.example.conf
------------------------------------------------------------
» sudo touch /etc/passwd
------------------------------------------------------------
» fg
[1]  + 7621 continued  sudo osqueryd --verbose --config_path ./build/osquery.example.conf
I0907 22:05:43.962143  7637 scheduler.cpp:75] Executing scheduled query file_events: select * from file_events;
I0907 22:05:44.012912  7637 scheduler.cpp:134] Found results for query: file_events
^Z
[1]  + 7621 suspended  sudo osqueryd --verbose --config_path ./build/osquery.example.conf
------------------------------------------------------------
» sudo cat /var/log/osquery/osqueryd.results.log
{"name":"file_events","hostIdentifier":"computer","calendarTime":"Fri Sep  8 05:05:44 2017 UTC","unixTime":"1504847144","epoch":"0","columns":{"action":"ATTRIBUTES_MODIFIED","atime":"1504847114","category":"passwd","ctime":"1504847114","gid":"0","hashed":"0","inode":"10110977","md5":"","mode":"0644","mtime":"1504847114","sha1":"","sha256":"","size":"2624","target_path":"\/etc\/passwd","time":"1504847116","transaction_id":"0","uid":"0"},"action":"added"}
{"name":"file_events","hostIdentifier":"computer","calendarTime":"Fri Sep  8 05:05:44 2017 UTC","unixTime":"1504847144","epoch":"0","columns":{"action":"UPDATED","atime":"1504847114","category":"passwd","ctime":"1504847114","gid":"0","hashed":"1","inode":"10110977","md5":"51486a69b34a9105867c25aa79d09e96","mode":"0644","mtime":"1504847114","sha1":"40a465b280f2619b13e029652f5480bf7ef74533","sha256":"0688cbe9277d30d6c490ec6c2998598ea6576159a284aee46d5fc2cbabb8cf39","size":"2624","target_path":"\/etc\/passwd","time":"1504847116","transaction_id":"0","uid":"0"},"action":"added"}
```

**Comment by waghi** [comment] 2018-03-06 05:57
@theopolis : can I schedule Distributed Queries??
