### ISSUE TITLE
no output from yum_sources

### ISSUE THREAD

**Issue by fossam** [facebook/osquery#4284] opened 2018-04-14 02:13 UTC
@Ngo-The-Trung I think you just recently contributed this table.

I built off of d27787e84f031ed17d0b20fb3165c1c49f125b5c and got a vanilla Centos7 VM, but I am having trouble getting output with:

> osqueryi  --version
> osqueryi version 3.2.2-14-gd27787e
> osqueryi  "select * from yum_sources ; "

The VM has the default repos and updates fine, so it has working yum repos.

**Comment by Ngo-The-Trung** [comment] 2018-04-14 03:37
Does it come out empty or does it crash?

This table only reads from `/etc/yum.conf` and files under `/etc/yum.repos.d`. Can you check if any of the files are there? The VM could have used a different dir.

If you the centos7 vm is publicly available you can put a link here I'll take a look.

**Comment by fossam** [comment] 2018-04-15 00:50
It comes out empty - it does not crash.
The VM is not publicly available, but it is a minimal install from the official iso with minimal changes. The osqueryi binary is copied from a build host.
Which install can you confirm it works on?

```
# ls  -1  /etc/yum.conf | xargs sha256sum
08310b191becc7d78ae04e8952d307439a61f94e43ff0a15df853a21566fbd5c  /etc/yum.conf
# rpm -ql yum --dump |grep /etc/yum.conf
/etc/yum.conf 970 1517320272 08310b191becc7d78ae04e8952d307439a61f94e43ff0a15df853a21566fbd5c 0100644 root root 1 0 0 X
# ls  -1  /etc/yum.repos.d/* | xargs sha256sum
0b0ac44db7a9798cd073fd3d60019242b7b1f3f35b33b1e1dc8b8c60f98744ac  /etc/yum.repos.d/CentOS-Base.repo
90ca35d17482fe28df0954c3a2ebb9727a1ebcd6a98a181039b807f6de8fd9c8  /etc/yum.repos.d/CentOS-CR.repo
4444c0b7a0eb2a9fe9f1348e1bb43108485174bcc03ac28d913da475eefb3889  /etc/yum.repos.d/CentOS-Debuginfo.repo
5d19c254501857abde689bba074f8dbc10ea6a31353dc36b913738180422bc28  /etc/yum.repos.d/CentOS-fasttrack.repo
6bd405d978eb64a53fb6bcb0d9e1a261c6f72602e602f31949c57445384bfb8b  /etc/yum.repos.d/CentOS-Media.repo
f2623d9807f80c797cef3d34d95a5306d15136704426e7866dbcbe1334f14bca  /etc/yum.repos.d/CentOS-Sources.repo
6f9c1d0aeb36bece5a3196f20e1c603b2c032f51ea6b9f939439becb24efd40f  /etc/yum.repos.d/CentOS-Vault.repo
# rpm -ql centos-release --dump |grep /etc/yum.repos.d | awk '{print $4" "$1}'
0b0ac44db7a9798cd073fd3d60019242b7b1f3f35b33b1e1dc8b8c60f98744ac /etc/yum.repos.d/CentOS-Base.repo
90ca35d17482fe28df0954c3a2ebb9727a1ebcd6a98a181039b807f6de8fd9c8 /etc/yum.repos.d/CentOS-CR.repo
4444c0b7a0eb2a9fe9f1348e1bb43108485174bcc03ac28d913da475eefb3889 /etc/yum.repos.d/CentOS-Debuginfo.repo
6bd405d978eb64a53fb6bcb0d9e1a261c6f72602e602f31949c57445384bfb8b /etc/yum.repos.d/CentOS-Media.repo
f2623d9807f80c797cef3d34d95a5306d15136704426e7866dbcbe1334f14bca /etc/yum.repos.d/CentOS-Sources.repo
6f9c1d0aeb36bece5a3196f20e1c603b2c032f51ea6b9f939439becb24efd40f /etc/yum.repos.d/CentOS-Vault.repo
5d19c254501857abde689bba074f8dbc10ea6a31353dc36b913738180422bc28 /etc/yum.repos.d/CentOS-fasttrack.repo
# yum info centos-release
Installed Packages
Name        : centos-release
Arch        : x86_64
Version     : 7
Release     : 4.1708.el7.centos
Size        : 37 k
Repo        : installed
From repo   : base
Summary     : CentOS Linux release file
License     : GPLv2
Description : CentOS Linux release files
```

Relevant selection of strace output:
```
open("/etc/yum.conf", O_RDONLY)         = 4
fstat(4, {st_mode=S_IFREG|0644, st_size=970, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8cfd3b8000
read(4, "[main]\ncachedir=/var/cache/yum/$"..., 4096) = 970
read(4, "", 4096)                       = 0
read(4, "", 4096)                       = 0
lseek(4, 0, SEEK_CUR)                   = 970
close(4)                                = 0
munmap(0x7f8cfd3b8000, 4096)            = 0
getcwd("/root", 128)                    = 6
stat("/etc/yum.repos.d/", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/", {st_mode=S_IFDIR|0555, st_size=4096, ...}) = 0
lstat("/etc", {st_mode=S_IFDIR|0755, st_size=8192, ...}) = 0
lstat("/etc/yum.repos.d", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/etc/yum.repos.d", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
openat(AT_FDCWD, "/etc/yum.repos.d", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 4
getdents(4, /* 9 entries */, 32768)     = 344
getdents(4, /* 0 entries */, 32768)     = 0
close(4)                                = 0
getuid()                                = 0
getgid()                                = 0
setresgid(-1, 0, -1)                    = 0
setresuid(-1, 0, -1)                    = 0
tgkill(14723, 14724, SIGRT_1)           = 0
setgroups(1, [0])                       = 0
futex(0x7f8cf0000984, FUTEX_CMP_REQUEUE_PRIVATE, 1, 2147483647, 0x7f8cf0000948, 2) = 1
futex(0x7f8cf0000948, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7f8cfe9eeb04, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x7f8cfe9eeb00, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
futex(0x7f8cfe9eead8, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7f8cfe9eea58, FUTEX_WAKE_PRIVATE, 1) = 1
close(3)                                = 0
exit_group(0)                           = ?
+++ exited with 0 +++
```

**Comment by fmanco** [comment] 2018-04-17 15:18
Hi @fossam I see what the problem is. We're looking at files with the `.list` extension, but your's have `.repo`. Could you just post the contents of `/etc/yum.conf` here please? Thank you!

**Comment by fossam** [comment] 2018-04-17 22:02
```
# cat /etc/yum.conf 
[main]
cachedir=/var/cache/yum/$basearch/$releasever
keepcache=0
debuglevel=2
logfile=/var/log/yum.log
exactarch=1
obsoletes=1
gpgcheck=1
plugins=1
installonly_limit=5
bugtracker_url=http://bugs.centos.org/set_project.php?project_id=23&ref=http://bugs.centos.org/bug_report_page.php?category=yum
distroverpkg=centos-release


#  This is the default, if you make this bigger yum won't see if the metadata
# is newer on the remote and so you'll "gain" the bandwidth of not having to
# download the new metadata and "pay" for it by yum not having correct
# information.
#  It is esp. important, to have correct metadata, for distributions like
# Fedora which don't keep old packages around. If you don't like this checking
# interupting your command line usage, it's much better to have something
# manually check the metadata once an hour (yum-updatesd will do this).
# metadata_expire=90m

# PUT YOUR REPOS HERE OR IN separate files named file.repo
# in /etc/yum.repos.d
```

Note that it shares the same hash as recorded in the upstream provided package metadata.
``` 
# sha256sum /etc/yum.conf
08310b191becc7d78ae04e8952d307439a61f94e43ff0a15df853a21566fbd5c  /etc/yum.conf
```

**Comment by Ngo-The-Trung** [comment] 2018-04-17 22:48
Yeah, I'm afraid that since the top level `/etc/yum.conf` doesn't have any repo, and the other files are named `.repo`, this will output nothing since I look for `.list` files.

We could relax this by removing the `.list` extension glob.

**Comment by fossam** [comment] 2018-04-18 03:41
Why are we looking for ```.list``` files? yum is always using ```.repo``` files (http://yum.baseurl.org/api/yum/yum/__init__.html?highlight=.repo#yum.__init__.YumBase.getReposFromConfig) 

```.list``` files are usually used by apt.

**Comment by HandIeNeeded** [comment] 2018-04-25 19:18
Merged the fix for this into master. Close the issue.

**Closed by HandIeNeeded** 2018-04-25 19:18 UTC
Labels: Linux, bug, virtual tables
